DaedalusDock/daedalusdock

code/_onclick/click.dm, code/game/objects/structures/low_wall.dm
Reverts DaedalusDock/Gameserver#9
=> Revert "Fix low walls being unpaintable while a window was on them"

.dockerignore, .github/guides/DOWNLOADING.md, .github/guides/RUNNING_A_SERVER.md, .github/guides/STANDARDS.md, .github/workflows/ci_suite.yml, .vscode/tasks.json, Dockerfile, README.md, SpacemanDMM.toml, code/__DEFINES/time.dm, code/controllers/configuration/entries/general.dm, code/datums/helper_datums/getrev.dm, code/game/world.dm, code/modules/mapping/mapping_helpers.dm, code/modules/reagents/chemistry/machinery/chem_mass_spec.dm, code/modules/surgery/organs/helpers.dm, code/modules/unit_tests/README.md, config/config.txt, config/motd.txt, daedalus.dme, tools/Upload tgstation.rsc to external FTP/upload_rsc.bat, tools/build/build.js, tools/ci/run_server.sh, tools/deploy.sh, tools/expand_filedir_paths.py, tools/tgs4_scripts/PreCompile.bat
:cl:
code: All tooling moved over to the daedalus name.
server: Scripts updated to the daedalus name.
/:cl:
=> Moves all of our tooling to the Daedalus name.

code/__DEFINES/rust_g.dm, dependencies.sh
=> Rustg update 68934-2

code/__DEFINES/atmospherics/ZAS.dm, code/__DEFINES/atmospherics/_UNUSED_OR_LEGACY_DEFINES.dm, code/__DEFINES/atmospherics/atmos_mob_interaction.dm, code/modules/atmospherics/machinery/components/binary_devices/temperature_gate.dm, code/modules/mob/living/carbon/human/species_types/zombies.dm
see title, nobody knew about the bug so 👍
=> Moves unused defines to a non-compiled file, and fixes a bug.

code/__DEFINES/atmospherics/_UNUSED_OR_LEGACY_DEFINES.dm, code/__DEFINES/atmospherics/atmos_machines.dm, code/modules/atmospherics/ZAS/atmos_primitives.dm, code/modules/atmospherics/machinery/atmosmachinery.dm, code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm, code/modules/atmospherics/machinery/components/binary_devices/pump.dm, code/modules/atmospherics/machinery/components/components_base.dm, code/modules/atmospherics/machinery/components/trinary_devices/filter.dm, code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm, code/modules/atmospherics/machinery/pipes/pipes.dm, code/modules/atmospherics/machinery/portable/pump.dm, code/modules/atmospherics/machinery/portable/scrubber.dm, daedalus.dme
Tweaked logic of some atmos processes, namely the mixer.
All "pumping" equipment now uses power based on the load, ENTROPY!!!
:cl:
add: Atmos pump power load is now based on entropy
tweak: Pipenets are "environmental" power to APCs
tweak: Gas Mixers logic adjusted.
/:cl:
=> Pipenet logic & power usage pass.

code/__DEFINES/span.dm, code/modules/mob/mob.dm, tgui/packages/tgui-panel/styles/goon/chat-dark.scss, tgui/packages/tgui-panel/styles/goon/chat-light.scss
Examining something now shows nearby (4 tile radius) mobs one of two things:
A. "John Doe looks at the supermatter crystal."
B. "John Doe looks intently at something..."
B occurs if the mob cannot see what John is looking at.
Huge meme potential for logs, as well as more RP potential.
:cl:
add: Nearby players can see when someone examines something.
/:cl:
=> Examine tweak

code/__DEFINES/lighting.dm
Players will barely notice a difference. But I do.
:cl:
tweak: Soft Lighting re-enabled.
/:cl:
=> Re-enables soft lighting

code/game/objects/structures/low_wall.dm
=> Attempts to fix low wall painting.

code/modules/surgery/bodyparts/dismemberment.dm, code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm, code/modules/surgery/organs/external/_external_organs.dm
Ports https://github.com/tgstation/tgstation/pull/66704
=> Port Tgstation PR#66704 - External organs can now contribute bodytypes to their owner

code/__DEFINES/space.dm, code/game/turfs/open/floor/fancy_floor.dm, code/game/turfs/open/space/space.dm, code/modules/holodeck/turfs.dm
Ports https://github.com/tgstation/tgstation/pull/69079
=> Ports Tgstation PR#69079 - Massively optimize space turf initializations (~20 seconds on Meta to ~3 seconds)

code/_onclick/hud/rendering/plane_master.dm
- https://github.com/tgstation/tgstation/pull/69778
I like being able to see the game
:cl:
server: Now supports 514.1587
/:cl:
=> Byond Version Bump: 1587

README.md, dependencies.sh
title.
:cl:
server: Updated some git stuff, don't worry about it.
/:cl:
=> Bump dependancies.sh, update readme

code/modules/atmospherics/ZAS/ConnectionGroup.dm
Yeah this doesnt fix the harddels themselves but I can do that later.
=> try to patch SSairflow fucking with unit tests

.github/workflows/ci_suite.yml
:cl:
server: Github Actions Dependency Update
/:cl:
=> Update DreamAnnotate Version

dependencies.sh
1589 is the recommended version to compile the codebase.
:cl:
server: Bumped recommended version to 1589
/:cl:
=> Bump BYOND version to 1589

code/modules/client/client_procs.dm
:cl:
server: Users who connect without a linked discord account will now get a pop-up.
/:cl:
=> Gives a pop-up for users who connect without a linked discord account

code/game/sound.dm
Ports https://github.com/tgstation/tgstation/pull/67989
:cl:
fix: fixed ghosts not hearing some sounds
/:cl:
=> Ghosts not hearing sounds fix

icons/dummy.dme
:cl:
code: ""QOL"" Change for spriters
/:cl:
=> Create dummy.dme in the icon tree

code/__DEFINES/paint.dm, code/modules/mapping/mapping_helpers.dm, code/modules/mob/inventory.dm, code/modules/mob/living/carbon/human/human_update_icons.dm, code/modules/mob/living/carbon/human/inventory.dm, code/modules/power/lighting/light.dm, modular_pariah/modules/aesthetics/lights/code/lighting.dm
I COULD'VE SWORN THIS WAS ALREADY DONE, WTF?????????????
:cl:
qol: Lighting has been dimmed
code: The wall paint mapping helpers now work for airlocks.
fix: Masks no longer poke through hats/helmets they shouldn't
/:cl:
=> Dims lighting... again?

code/modules/antagonists/cult/cult_items.dm, code/modules/shuttle/emergency.dm
Title
The shuttle takes too long.
:cl:
tweak: Reduced the emergency shuttle timers.
/:cl:
=> Decreases the Shuttle timer to 10/5/5 down from 20/10/5

.gitignore, code/controllers/admin.dm, code/controllers/subsystem/credits.dm, code/controllers/subsystem/ticker.dm, code/game/sound.dm, code/modules/admin/admin_verbs.dm, code/modules/credits_roll/episode_name.dm, config/credits_music/README.txt, config/credits_music/jsons/EXAMPLE.json, config/title_music/EXAMPLE.json, config/title_music/jsons/EXAMPLE.json
Cleans up music code and adds `Change Title Music` verb to the "fun" sub-category of the Admin tab
:cl:
code: Clean up title music code
code: Title Music and Credits Music are now independent concepts
add: Change Title Music verb for admins.
/:cl:
=> Clean up music code

code/modules/events/immovable_rod.dm
the sound the immovable rod makes when it collides with something is a variable
was disappointed to find that changing this sound can't be done in game.
=> Immovable Rod sound is now a variable

code/__DEFINES/atmospherics/atmos_machines.dm, code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm, code/modules/atmospherics/machinery/components/binary_devices/pressure_valve.dm, code/modules/atmospherics/machinery/components/binary_devices/pump.dm, code/modules/atmospherics/machinery/components/binary_devices/temperature_gate.dm, code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm, code/modules/atmospherics/machinery/portable/pump.dm, code/modules/atmospherics/machinery/portable/scrubber.dm
pump_gas() returns -1 when no gas is moved, not 0.
:cl:
fix: Semi-rare bug involving pumps not pumping.
/:cl:
=> (Attempts to) Fix a somewhat rare issue with pipenets not being updated

.github/workflows/ci_suite.yml, .github/workflows/conflicts.yml
Requested by Kapu. See tgstation/tgstation#71601 for more information.
=> Impliment Project Branches

code/__DEFINES/waddling.dm, code/datums/ai/objects/vending_machines/vending_machine_controller.dm, code/modules/clothing/shoes/clown.dm, code/modules/mob/living/carbon/human/species_types/teshari.dm, code/modules/mob/living/simple_animal/friendly/penguin.dm, code/modules/mob/living/simple_animal/hostile/regalrat.dm, code/modules/mod/modules/modules_service.dm, code/modules/surgery/organs/ears.dm, code/modules/vehicles/cars/clowncar.dm, daedalus.dme
:cl:
add: Teshari move funny
/:cl:
=> Teshari waddle + small waddle refactor

_maps/atlas.json, _maps/map_files/Atlas/atlas.dmm, _maps/shuttles/mining_atlas.dmm, code/datums/shuttles.dm, daedalus.dme
Also added the Mining shuttle.
=> [ATLAS] Start on Cargo, Botany, and Mining. Give Atmos about 70% more space.

code/game/area/areas/ruins/space.dm, code/game/area/space_station_13_areas.dm, code/game/turfs/open/space/space.dm, code/modules/events/aurora_caelus.dm, config/game_options.txt
The changes to lighting inadvertently neutered starlight. This changes that.
:cl:
fix: Starlight does something again
/:cl:
=> Fixes starlight

code/__DEFINES/dynamic.dm, code/__HELPERS/roundend.dm, code/game/machinery/computer/communications.dm, code/modules/admin/check_antagonists.dm, code/modules/antagonists/revolution/revolution.dm, code/modules/antagonists/wizard/equipment/spellbook.dm, code/modules/credits_roll/episode_name.dm
This PR adds some if statements to check if it's dynamic game mode (prevents runtimes when using a different game mode)
Compatibility and we also need this for https://github.com/DS-13-Dev-Team/Daedalus_Dock \*sweat_smile*
:cl:
code: dynamic game mode is less hardcoded now
/:cl:
=> Makes dynamic game mode less hardcoded 

.github/workflows/generate_documentation.yml
No CL, Repo Organizational Change.
=> Properly set the documentation page CNAME.

code/modules/client/preferences/species_features/teshari.dm, code/modules/surgery/organs/external/_external_organs.dm
:cl:
fix: Teshari feather coloration
/:cl:
=> Fix teshari feathers not using hair color

code/game/area/space_station_13_areas.dm
This should hopefully squash this once and for all
:cl:
/:cl:
=> the test area REALLLLLLYYY WANTS LIGHT

code/_onclick/telekinesis.dm, code/datums/components/surgery_initiator.dm
title
:cl:
qol: Surgery stage messages have been moved to the chat.
/:cl:
=> remove balloon alerts from surgery

code/modules/mob/dead/observer/observer.dm
:cl:
fix: The living no longer see the dead stalk the halls.
/:cl:
=> ghosts are invisible to the living again

code/controllers/subsystem/movement/movement.dm
- https://github.com/tgstation/tgstation/pull/66532
:cl:
/:cl:
=> Enables out of order moveloop removal

code/modules/atmospherics/ZAS/XGM/gases.dm, code/modules/unit_tests/_unit_tests.dm, code/modules/unit_tests/gas_validation.dm
I love how this is technically valid behavior, but its a bug.
:cl:
fix: Removed Nullium
/:cl:
=> Fix the null gas

_maps/_basemap.dm, _maps/atlas.json, _maps/map_files/Atlas/atlas.dmm, code/_compile_options.dm, code/datums/shuttles.dm
=> [ATLAS] More work on Cargo

code/modules/atmospherics/ZAS/Zone.dm, code/modules/power/apc/apc_main.dm, code/modules/shuttle/emergency.dm, code/modules/shuttle/shuttle.dm
=> Fix null in atmos_sensitive_contents list

code/__DEFINES/atmospherics/ZAS_math.dm, code/game/objects/items/grenades/atmos_grenades.dm, code/modules/atmospherics/ZAS/Turf.dm, code/modules/mob/living/simple_animal/hostile/regalrat.dm, code/modules/reagents/chemistry/reagents/other_reagents.dm, code/modules/reagents/chemistry/recipes/others.dm, code/modules/reagents/chemistry/recipes/pyrotechnics.dm, code/modules/reagents/chemistry/recipes/slime_extracts.dm, code/modules/research/xenobiology/crossbreeding/burning.dm, code/modules/research/xenobiology/xenobiology.dm
They were never adjusted to ZAS.
:cl:
fix: Chemicals that were not adding gas to the atmosphere properly, now do so.
/:cl:
=> Fix all uses of atmos_spawn_air()

_maps/map_files/MetaStation/MetaStation.dmm
fixes the apc
:cl:
fix: The Bar APC is now wired roundstart.
/:cl:
=> fix the apc

code/datums/components/overlay_lighting.dm, code/game/machinery/doors/airlock.dm, code/modules/lighting/lighting_source.dm
- https://github.com/tgstation/tgstation/pull/70578
- https://github.com/tgstation/tgstation/pull/69758
- https://github.com/tgstation/tgstation/pull/72148
:cl: Tastyfish, ChungusGamer666
fix: Flashlights and similar directional light items no longer make you glow forever under certain circumstances.
add: The all-access indicator is now glow in the dark.
fix: Some lights that would fail to follow the light source have been fixed.
/:cl:
=> Fix some weirdness with regards to lighting

code/modules/clothing/spacesuits/plasmamen.dm
:cl:
fix: The plasmaman helmet "Toggle Welding Screen" button works.
/:cl:
=> Fixes the plasmaman welding screen action button

code/modules/mob/dead/observer/observer.dm
it adds KEEP_TOGETHER
:cl:
fix: Ghosts look correct.
/:cl:
=> Makes Carbon ghosts consistent with their living body

tgui/package.json, tgui/yarn.lock
- https://github.com/tgstation/tgstation/pull/73457
=> Bump webpack version

html/changelogs/AutoChangeLog-pr-163.yml
We've been carrying this broken stub around since pariah
=> Broken AutoCL Deletion

code/__DEFINES/mobs.dm
yea
:cl:
balance: Hunger decreases 5x slower.
/:cl:
=> Reduce hunger by a factor of 5

code/controllers/subsystem/mapping.dm, code/modules/mapping/space_management/multiz_helpers.dm
We've needed them in like 5 prs already fuck this.
Cherrypicks the zstack helpers from #189
:cl:
code: new ways to make zstack checks not suck
/:cl:
=> Cherrypicks the zstack helpers from #189

code/game/objects/items/storage/bags.dm
You can now once again put pills and patches into chemistry bags.
:cl:
fix: Chemistry bags now accept pills and patches
/:cl:
=> re-adds pills/patches to chemistry bags

code/datums/ai_laws.dm, code/game/objects/effects/spawners/random/ai_module.dm, code/game/objects/items/AI_modules.dm, config/game_options.txt
:cl:
server: Changed Asimov and Crewsimov laws. Read carefully.
/:cl:
=> Updates AI Laws

code/game/atoms_movable.dm, code/game/machinery/doors/door.dm, code/game/machinery/doors/windowdoor.dm, code/game/machinery/shieldgen.dm, code/game/objects/effects/effect_system/effects_foam.dm, code/game/objects/structures/holosign.dm, code/game/objects/structures/mineral_doors.dm, code/game/objects/structures/windoor_assembly.dm, code/game/objects/structures/window.dm, code/modules/antagonists/blob/structures/_blob.dm, code/modules/atmospherics/ZAS/Atom.dm, code/modules/atmospherics/ZAS/zas_extras/inflatable.dm, code/modules/recycling/conveyor.dm
- https://github.com/tgstation/tgstation/pull/67456
- https://github.com/tgstation/tgstation/pull/70352
:cl: MrMelbert, Kapu1178, ShizCalev
fix: Light switches no longer cause anchored objects over conveyors to move.
fix: Doors no longer trigger zone updates if they didn't move.
code: Fixed alot of extra zas_update_loc() calls
/:cl:
=> Conveyer bugs

code/modules/mob/living/carbon/human/human_update_icons.dm
quick port of tgstation/tgstation/pull/66646
fixes #268 quickly before the next test.
:cl:
fix: Female worn clothing displays as intended again
/:cl:
=> Fixed female fitted uniforms not being fitted for female bodies (#66646)

code/modules/shuttle/navigation_computer.dm, code/modules/shuttle/syndicate.dm
Fixes shuttle docking do_after
Fixes syndicate shuttle having messed up camera offsets
Fixes shuttle location designator not showing above space
Lets fix these before the players notice!
:cl:
fix: Fixed several issues with shuttle navigation
/:cl:
=> Fixes some shuttle things

.github/workflows/ci_suite.yml
https://github.com/tgstation/tgstation/pull/74380
sure hope this doesnt need github changes @francinum
=> 515 tests dont block merge

code/controllers/subsystem/processing/processing.dm, code/modules/antagonists/pirate/pirate.dm, code/modules/atmospherics/ZAS/Fire.dm, code/modules/clothing/masks/hailer.dm, code/modules/explorer_drone/exodrone.dm, code/modules/food_and_drinks/restaurant/custom_order.dm, code/modules/mafia/controller.dm, code/modules/mapfluff/ruins/lavalandruin_code/puzzle.dm, code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm, code/modules/power/data_terminal.dm, code/modules/power/singularity/narsie.dm, code/modules/power/tesla/energy_ball.dm, code/modules/spells/spell_types/right_and_wrong.dm, code/modules/surgery/bodyparts/injuries.dm, code/modules/surgery/organs/tongue.dm, code/modules/wiremod/components/list/format.dm, modular_pariah/modules/hyposprays/code/hyposprays_II.dm
:cl:
code: More 515 compatibility. Nothing to see here, folks.
/:cl:
=> Finalize(?) 515 compat

code/modules/explorer_drone/exodrone.dm, code/modules/wiremod/components/list/format.dm
:cl:
fix: Circuit shit nobody uses anyway.
/:cl:
=> fixes regex replace

code/modules/client/client_procs.dm
:cl:
server: Patched a security hole
/:cl:
=> [s]Disable byond debug links (#74373)

_maps/RandomRuins/SpaceRuins/TheDerelict.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/debug/atmos_mintest.dmm, _maps/map_files/debug/multiz.dmm, _maps/map_files/debug/runtimestation.dmm, code/__DEFINES/turfs.dm, code/controllers/subsystem/mapping.dm, code/modules/mapping/space_management/multiz_helpers.dm, code/modules/mob/living/init_signals.dm, code/modules/power/gravitygenerator.dm, code/modules/power/supermatter/nupermatter.dm, code/modules/shuttle/on_move.dm, unused_maps/map_files/Deltastation/DeltaStation2.dmm, unused_maps/map_files/KiloStation/KiloStation.dmm, unused_maps/map_files/PubbyStation/PubbyStation.dmm, unused_maps/map_files/multizas_debug/atmos_mintest_mz_1.dmm
- https://github.com/tgstation/tgstation/pull/67586
:cl:
fix: The gravity generator properly updates gravity during init.
/:cl:
=> Fixes maploaded mobs appearing floating

code/controllers/subsystem/credits.dm, code/controllers/subsystem/ticker.dm
The scroll speed is based on how slow the client is running, I think, due to being javascript in a browser element. So let's just make it go maximum speed.
:cl:
fix: Credits run after a delay properly.
tweak: Credits scroll faster.
/:cl:
=> Fix credits roll delay and increases scroll speed.

code/modules/projectiles/guns/ballistic/revolver.dm
Fixes
* https://github.com/DaedalusDock/daedalusdock/issues/304
Used as a reason to get my VM and tools set up tm 
It makes for a lousy easter egg
:cl: Froststahr
fix: The detective's revolver now uses the proper icon.
/:cl:
=> Fixes the detective revolver icon

code/modules/surgery/organs/lungs.dm
This runtime is harmless but is a runtime. Breath can be null.
:cl:
code: Fixed an invisible runtime.
/:cl:
=> Fixes slimeperson lung runtime

code/modules/mob/living/living_movement.dm
- https://github.com/tgstation/tgstation/pull/75333
:cl: san7890
fix: Gravity runtime
/:cl:
=> fix gravity runtime

code/controllers/subsystem/zas.dm
=> Fix runtime in zas.dm

code/modules/client/client_procs.dm
- https://github.com/tgstation/tgstation/pull/70386
:cl: Gamer025
fix: You should no longer receive "Your previous action was ignored..." messages when you join a server
/:cl:
=> Fix per-second topic limiter

code/modules/atmospherics/machinery/components/binary_devices/circulator.dm, code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm, code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm, code/modules/atmospherics/machinery/components/binary_devices/pressure_valve.dm, code/modules/atmospherics/machinery/components/binary_devices/pump.dm, code/modules/atmospherics/machinery/components/binary_devices/temperature_gate.dm, code/modules/atmospherics/machinery/components/trinary_devices/filter.dm, code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm, code/modules/atmospherics/machinery/datum_pipeline.dm, code/modules/power/generator.dm
:cl:
fix: ZAS Bugs, pumps should be notably stronger.
/:cl:
=> Atmos Fixes

code/modules/mob/living/silicon/ai/ai.dm
Fixes the camera light toggle bricking cam lights.
:cl:
fix: AI camera light toggle will no longer break camera lights forever.
/:cl:
=> Fixes AI camera lights

code/datums/elements/plant_backfire.dm, code/datums/status_effects/debuffs/fire_stacks.dm, code/modules/flufftext/Hallucination.dm, code/modules/hydroponics/unique_plant_genes.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/silicon/silicon.dm, code/modules/unit_tests/_unit_tests.dm, code/modules/unit_tests/novaflower_burn.dm
Ports:
- https://github.com/tgstation/tgstation/pull/67096
- https://github.com/tgstation/tgstation/pull/67597
- https://github.com/tgstation/tgstation/pull/72843
Semi-Ports:
- https://github.com/tgstation/tgstation/pull/73601
:cl:
fix: RDS no longer burns your clothes off.
/:cl:
=> Fixes bugs with Fire.

code/game/machinery/embedded_controller/airlock_controller.dm
This paves the way for more work on these. I just needed to clean my branch
:cl:
del: Airlock controller UIs are reverted to HTML
/:cl:
=> Revert airlock controller UI to HTML

code/__DEFINES/dcs/signals/signals_atom/signals_atom_movable.dm, code/__DEFINES/stamina.dm, code/_globalvars/phobias.dm, code/datums/ai/monkey/monkey_controller.dm, code/datums/components/carbon_sprint.dm, code/game/atoms_movable.dm, code/game/machinery/camera/tracking.dm, code/game/objects/items/storage/belt.dm, code/game/turfs/turf.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm, code/modules/clothing/suits/bio.dm, code/modules/clothing/suits/labcoat.dm, code/modules/clothing/suits/wintercoats.dm, code/modules/jobs/job_types/captain.dm, code/modules/jobs/job_types/chief_engineer.dm, code/modules/jobs/job_types/chief_medical_officer.dm, code/modules/jobs/job_types/head_of_personnel.dm, code/modules/mob/inventory.dm, code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm, code/modules/mob/mob.dm, code/modules/mod/mod_theme.dm, code/modules/surgery/organic_steps.dm, code/modules/vehicles/trolley.dm, config/game_options.txt
:cl:
balance: Heads lost Telebatons and gained Flashes
balance: Reduced the blast speed of heirophant's blasts.
balance: Reduced the stamina cost of sprinting
balance: Reduced the speed of sprinting
qol: Sprinting no longer drains stamina if you aren't able to move in that direction.
/:cl:
=> Balance Changes

code/__DEFINES/loadout.dm, code/modules/client/preferences/html_prefs/categories/loadout.dm, code/modules/client/preferences/loadout/loadout_item/backpack.dm, code/modules/client/preferences/loadout/loadout_item/mask.dm
Adds a bunch of items and some new items from before the loadout refactor. Includes plushies, lipstick, skateboard, instrument beacon, and breath masks plus a security mask
I can have a Purple vox breathing mask to match my purple skirt and also everyone can have some funny plushies to play with.
:cl:
add: A bunch of old loadout items
add: A few new masks 
fix: You can see which jobs let you use certain items
/:cl:
=> Re-adds and adds a few more items to loadout

code/__DEFINES/zmimic.dm, code/controllers/subsystem/zcopy.dm, code/modules/mob/living/carbon/carbon_update_icons.dm, code/modules/mob/living/living_update_icons.dm
idk why it doesnt work, i think byond hates while loops. disabled.
=> Disable z_animate

code/__DEFINES/spatial_gridmap.dm, code/controllers/subsystem/spatial_gridmap.dm, code/game/atoms_movable.dm, code/game/turfs/open/lava.dm, code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
- https://github.com/tgstation/tgstation/pull/75161
- https://github.com/tgstation/tgstation/pull/75658
:cl: Kylerace
fix: Extremely rare and horrific bug relating to the spatial gridmap
/:cl:
=> Spatialgridports

code/modules/surgery/bodyparts/_bodyparts.dm, code/modules/surgery/bodyparts/dismemberment.dm, code/modules/surgery/bodyparts/head.dm, code/modules/surgery/organs/_organ.dm, code/modules/surgery/organs/tongue.dm, code/modules/unit_tests/codex.dm
This is why dismembering a head keeps you alive. 
:cl:
fix: Decapitation is now lethal again.
fix: Tongueless speech works again.
/:cl:
=> Fix dismemberment not removing organs from the owner.

code/modules/surgery/bodyparts/dismemberment.dm, code/modules/surgery/healing.dm, code/modules/unit_tests/surgeries.dm
:cl:
tweak: You must expose your flesh to be healed by tend wounds.
/:cl:
=> get naked, get healed

code/_compile_options.dm, code/modules/surgery/bodyparts/dismemberment.dm, code/modules/surgery/bodyparts/head.dm, code/modules/surgery/organs/_organ.dm
Brain code is so fucked up. It should be less fucked up now. Still fucked up though. Fuck.
:cl:
qol: Surgically attaching your head to a body no longer sends your brain to [DATA EXPUNGED]
/:cl:
=> Fixes head attachment sending the brain to nullspace.

code/_compile_options.dm, code/modules/admin/verbs/SDQL2/SDQL_2.dm
- https://github.com/tgstation/tgstation/pull/76276
- https://github.com/tgstation/tgstation/pull/76275
:cl: MrStonedOne
server: Security improvement.
/:cl:
=> MrMaintenanceOne PRs

code/__DEFINES/paint.dm
:cl:
tweak: Darkened the color of the Daedalus walls.
/:cl:
=> darken wall paint

code/game/turfs/closed/minerals.dm, code/modules/client/verbs/looc.dm, code/modules/mob/living/carbon/human/species.dm
:cl:
fix: Disablers like, do stamina damage.
fix: LOOC can be used while in soft crit
/:cl:
=> Fix a couple bugs

code/controllers/subsystem/zas.dm, code/modules/atmospherics/ZAS/XGM/xgm_gas_mixture.dm
Optimizes `copyFrom()`. No idea why it was written how it was.
Additionally, quantizes all gas movement. This *does* reduce accuracy a tiny bit, but also, we're dealing with float32, accuracy was already out the window. This will prevent comically small values from persisting in gas.
:cl:
balance: All air mixture values are rounded to 0.0001.
/:cl:
=> ZAS Optimizations and Improvements

code/__DEFINES/qdel.dm, code/__DEFINES/zmimic.dm, code/__HELPERS/areas.dm, code/_compile_options.dm, code/controllers/subsystem/atoms.dm, code/controllers/subsystem/timer.dm, code/controllers/subsystem/zcopy.dm, code/game/atoms_movable.dm, code/game/machinery/limbgrower.dm, code/game/objects/effects/temporary_visuals/temporary_visual.dm, code/game/objects/items/implants/implant_track.dm, code/modules/mapping/reader.dm, code/modules/mob/living/living.dm, code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm, code/modules/zmimic/mimic_movable.dm
- https://github.com/tgstation/tgstation/pull/76214
- https://github.com/tgstation/tgstation/pull/76179
- https://github.com/tgstation/tgstation/pull/76241
- https://github.com/tgstation/tgstation/pull/68493
:cl: LemonInTheDark, Guillaume Prata
fix: Maps loaded post init will no longer randomly enter a failed state. Hopefully.
qol: Be polite! While on walk intent you won't bump, swap places or push other people now.
/:cl:
=> Speed and Bugfix ports

code/modules/research/designs/AI_module_designs.dm, code/modules/research/designs/comp_board_designs.dm, code/modules/research/designs/machine_designs.dm, code/modules/research/designs/mecha_designs.dm, code/modules/research/designs/mining_designs.dm, code/modules/research/designs/power_designs.dm, code/modules/research/designs/telecomms_designs.dm
closes #371 
:cl:
fix: Alot of circuitboards that were unobtainable are obtainable again via the circuit imprinter.
/:cl:
=> Fixes a ton of circuitboards being unobtainable

code/datums/elements/ridable.dm, code/modules/zombie/items.dm
:cl:
fix: A bug with zombie hands, pay no mind
/:cl:
=> fix zombie hands

code/game/objects/items/dehy_carp.dm, code/modules/mob/living/simple_animal/hostile/megafauna/_megafauna.dm, code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm, code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
:cl:
balance: Megafauna no longer gib dead players.
/:cl:
=> Megafauna no longer gib people

code/modules/projectiles/guns/ballistic/revolver.dm
:cl:
fix: Detective's revolver is no longer an error
del: Detective's revolver is no longer reskinnable
/:cl:
=> fix det revolver

code/game/machinery/computer/Operating.dm, code/modules/research/designs/medical_designs.dm, code/modules/unit_tests/designs.dm
:cl:
fix: Removed a phantom surgery from the operating console
/:cl:
=> Fix phantom surgery entry in the operating console

code/game/objects/items/devices/scanners/health_analyzer.dm, code/modules/mob/living/carbon/damage_procs.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/surgery/bodyparts/_bodyparts.dm
:cl:
fix: Examining someone now shows broken bones.
qol: Health Analyzers now display broken bones.
fix: Checking yourself for injuries now shows broken bones even if the limb has no damage.
/:cl:
=> human examine improvements

code/datums/progressbar.dm, code/modules/surgery/organs/autosurgeon.dm
:cl:
fix: do_after() now renders on the correct layer and plane
fix: Auto surgeon do_after()
/:cl:
=> 2 do_after() bugs

code/game/atoms_movable.dm
:cl:
fix: You can no longer get to centcom from the station with one verb.
/:cl:
=> fuck fuck fuck fuck fuck fuck

code/__HELPERS/hearted.dm
Shuffles JPL before doing commendation poll selection.
:cl:
fix: Commendation polling was asking people in the order they joined the server. It will now instead pick randomly.
/:cl:
=> Debiases commendation polling

code/controllers/subsystem/overlays.dm
A
:cl:
fix: Energy guns display charge again. Probably a few other things as well, Overlay rendering was fucked:tm:
/:cl:
=> Fixes build_appearance_list not preserving order

tgui/packages/tgui-dev-server/reloader.js
- https://github.com/tgstation/tgstation/pull/71374
=> fixes tgui dev for 514

code/game/machinery/syndicatebomb.dm, code/game/objects/items/defib.dm, code/game/objects/items/grenades/syndieminibomb.dm, code/game/objects/items/storage/holsters.dm, code/game/objects/items/tools/crowbar.dm, code/game/objects/structures/bedsheet_bin.dm, code/modules/clothing/masks/gasmask.dm, code/modules/mod/mod_theme.dm, code/modules/paperwork/stamps.dm, code/modules/reagents/reagent_containers/bottle.dm, code/modules/uplink/uplink_items/suits.dm
:cl:
qol: Removed the "syndicate" prefix from some items.
/:cl:
=> Remove the "Syndicate" prefix from some items

.gitignore, code/_compile_options.dm, code/game/world.dm, code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm, code/modules/surgery/bodyparts/_bodyparts.dm
:cl:
code: Daedalus now supports the Byond-Tracy profiler.
fix: Fixed a serious bug with bodypart damage.
/:cl:
=> Add Byond Tracy support, fix a bug

code/controllers/subsystem/atoms.dm, code/modules/mob/living/carbon/life.dm
:cl:
fix: Specific chemical effects no longer last forever
fix: ZMimic failing to recognize new atoms
/:cl:
=> hotfix 2 bugs

code/_onclick/hud/fullscreen.dm
The Midnight Society has said maintenance is not spooky enough. I must oblige.
:cl:
tweak: Player darksight is now DRASTICALLY weaker.
/:cl:
=> Make the dark darker

code/controllers/subsystem/atoms.dm
:cl:
code: TESTING mode works again.
/:cl:
=> Fixes TESTING mode

code/__DEFINES/robots.dm, code/__HELPERS/atoms.dm, code/datums/components/wearertargeting.dm, code/modules/mob/living/simple_animal/bot/mulebot.dm, code/modules/unit_tests/atmos_moles_tests.dm, code/modules/unit_tests/find_reference_sanity.dm, tgui/packages/tgui/interfaces/Mule.js
Port of https://github.com/tgstation/tgstation/pull/67860
:cl: SmoSmoSmoSmok
fix: mulebots can be turned on/off
/:cl:
fixes #444
=> Mulebotfix

code/modules/surgery/new_surgery/dental_implant.dm, code/modules/surgery/organs/_organ.dm
:cl:
fix: In some cases organs would be unable to be coupled to a mob, these have been fixed.
/:cl:
=> Fix organ bug

code/__DEFINES/reagents.dm
:cl:
balance: Addiction phases changed to 10/20/40 minutes from 1/2/3 minutes.
/:cl:
=> addiction rebalance

code/modules/mob/living/simple_animal/friendly/cat.dm
:cl:
add: Added a chance for Runtime to spawn with a different name.
/:cl:
=> Alternative Runtime name

code/modules/admin/verbs/deadsay.dm
:cl:
admin: DSAY now autocompletes again.
/:cl:
=> Unmarks dsay as hidden

code/modules/mob/living/living.dm
:cl:
fix: Non-human living mobs can now look up
/:cl:
=> Fixes verb scope on Look Upwards

.gitignore, code/controllers/configuration/entries/comms.dm, code/modules/admin/sql_ban_system.dm, config/comms.txt, config/config.txt, interface/interface.dm
Allows issues to be reported in-game, and more importantly,
Getting players to report issues is hard. This makes it easier.
:cl:
qol: The Report Issues Button no longer sends you to github, but instead sends the issue report itself.
/:cl:
=> In-Game github Issue Reporter

code/__DEFINES/dcs/signals/signals_global.dm, code/datums/datacore.dm, code/game/objects/items.dm, code/game/objects/items/cards_ids.dm, code/modules/jobs/job_types/_job.dm, code/modules/mob/dead/new_player/new_player.dm, code/modules/mob/living/carbon/human/examine.dm
:cl:
del: IDs are no longer named after the owner.
add: IDs can now be examined to see lots of information about the registered employee.
add: Chameleon IDs now have an "Impersonate Crew" button, to clone the target's ID.
/:cl:
=> Baystation-style IDs

code/controllers/subsystem/processing/instruments.dm
:cl:
fix: Instruments work again
/:cl:
=> Fixes instruments

code/modules/mob/living/blood.dm, code/modules/reagents/chemistry/reagents/dispenser_reagents.dm
:cl:
fix: Ingesting iron no longer marks you for blood-gib.
/:cl:
=> fixes iron setting blood to the lethal limit instantly

code/__DEFINES/packetnet.dm, code/game/machinery/datanet/_networked.dm, code/game/machinery/datanet/p2p_phones/_p2p_phones.dm
=> Packetnet defines

code/game/machinery/doors/door.dm, code/modules/atmospherics/ZAS/Atom.dm, code/modules/atmospherics/ZAS/Debug.dm, code/modules/atmospherics/ZAS/Turf.dm, code/modules/atmospherics/ZAS/XGM/xgm_gas_mixture.dm, code/modules/atmospherics/ZAS/Zone.dm, code/modules/atmospherics/ZAS/zas_extras/inflatable.dm
=> Revert "Fixes a decade old ZAS issue (#483)"

code/modules/uplink/uplink_items/device_tools.dm
my ears ded
Discounts bypass stocking, and at max discount, you can buy 20 of the fucking things.
No.
:cl:
balance: Crab-17 Phones can no longer go on discount.
/:cl:
=> no more cheap crabs

code/__HELPERS/mobs.dm, code/__HELPERS/stoplag.dm, code/_onclick/hud/radial.dm, code/controllers/subsystem/circuit_component.dm, code/controllers/subsystem/throwing.dm, code/datums/callback.dm, code/datums/cinematic.dm, code/datums/components/action_item_overlay.dm, code/datums/components/anti_magic.dm, code/datums/components/effect_remover.dm, code/datums/components/food/edible.dm, code/datums/components/jetpack.dm, code/datums/components/material_container.dm, code/datums/components/mind_linker.dm, code/datums/components/rotation.dm, code/datums/components/shielded.dm, code/datums/components/singularity.dm, code/datums/components/tippable.dm, code/datums/helper_datums/events.dm, code/game/machinery/sheetifier.dm, code/modules/events/wizard/greentext.dm, code/modules/security_levels/keycard_auth/keycard_authentication.dm
- https://github.com/tgstation/tgstation/pull/77850
- https://github.com/tgstation/tgstation/pull/77868
=> LITD Fixes

code/game/machinery/datanet/p2p_phones/_p2p_phones.dm
This code is awful and the real answer is to rewrite it, but I need to set aside an entire few days for that, and just can't right now.
:cl:
fix: Phones should more accurately reflect their state visually.
/:cl:
=> Small tweak to phone icon state handling

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/human/species.dm, code/modules/mob/living/life.dm
:cl:
add: Being in a low or high pressure environment now damages your eyes and ears.
/:cl:
=> pressure damage now hurts your ears and eyes

_maps/map_files/MetaStation/MetaStation.dmm, code/modules/reagents/reagent_containers/glass.dm
First: Updates beaker transfer amounts for their new storage amounts. Beakers can now transfer 30/60u at a time, large beakers can do 40 etc.
Second: Adds plasma and an all-in-one-grinder to chemistry
Less painful to work with. Missing things re-added.
:cl:
add: Chemistry gets a grinder and plasma by default
qol: updates beaker transfer amounts for the multiple-of-sixtyening.
/:cl:
=> A couple little medbay things

code/datums/components/acid.dm, code/game/area/areas.dm
=> 2 tiny bugs

code/_compile_options.dm
=> Fixes the live ref tracker

code/controllers/subsystem/processing/singulo.dm, code/controllers/subsystem/weather.dm, code/datums/components/singularity.dm, code/datums/weather/weather.dm, code/modules/power/supermatter/nupermatter.dm, code/modules/power/supermatter/nupermatter_hit_procs.dm
:cl:
fix: Supermatter delamination properly triggers a radiation storm.
/:cl:
=> fixes supermatter delam stuff

code/modules/atmospherics/ZAS/zas_extras/inflatable.dm
=> Fix a non-usage of PROC_rEF

code/datums/components/crafting/crafting.dm, code/game/objects/structures/headpike.dm
:cl:
fix: You can't make a headpike out of your own head anymore.
/:cl:
=> You can no longer use your own organs and bodyparts in crafting

interface/interface.dm
=> Fix formatting on client information

code/game/objects/items/storage/medkit.dm
:cl:
fix: Dermaline and Meralyne pill bottles have the correct pills.
/:cl:
=> fix pillbottle fuckies

code/modules/reagents/chemistry/machinery/chem_master.dm, tgui/packages/tgui/interfaces/ChemMaster.js
I fucking hate tgui so much
Doubles the amount of pills/patches whatever you can make at once in the chemmaster to 20
I need to split 120u beakers into 10u pills and if I have to split it up into 100 + 20 units again so help me god.
:cl:
qol: chemmaster can now make twice the amount of things at once
/:cl:
=> increases chemmaster max pill amount

code/game/turfs/change_turf.dm
:cl:
fix: Fixed an issue where rarely fires could burn forever.
/:cl:
=> turfs remember their fire post changeturf

code/controllers/subsystem/credits.dm, code/modules/credits_roll/credits.html
:cl:
refactor: Credits should now consistently reach the bottom of the screen. Even if a bit.... choppily.
/:cl:
=> Refactor credits javascript handler

code/modules/paperwork/ticketmachine.dm
Greatly simplifies code, demagicks ticket machines.
:cl:
del: Ticket machine tickets no longer magically vanish upon deletion, and the entire logic chain is generally much simpler.
/:cl:
=> Removes ticket tracking and notification logic

code/game/objects/effects/decals/decal.dm
:cl:
fix: Turf Decals are now anchored.
/:cl:
=> Turf Decals are anchored

code/_globalvars/lists/maintenance_loot.dm, code/controllers/subsystem/garbage.dm, code/controllers/subsystem/mapping.dm, code/game/objects/effects/misc.dm, code/game/objects/effects/spawners/costume.dm, code/game/objects/effects/spawners/random/entertainment.dm, code/game/objects/effects/spawners/random/maintenance.dm, code/game/objects/effects/spawners/random/random.dm
At least some of https://github.com/tgstation/tgstation/pull/70729
fixes #562 
:cl:
fix: maint loot spawners should work again.
/:cl:
=> ports various missing parts of TG PRs

code/game/objects/items/manuals.dm
:cl:
fix: Wiki Books now render (more) properly
fix: Space Law book points to Corporate Regulations.
/:cl:
fuck you i am gjsdbriarceonuns i am god
=> Wiki Book rendering update

code/__DEFINES/flags.dm, code/__HELPERS/lighting.dm, code/datums/elements/decals/_decal.dm, code/game/atoms.dm, code/game/atoms_movable.dm, code/modules/lighting/lighting_corner.dm
:cl:
code: Added a high pass filter to bloom to cull useless overlays, should help performance alot.
/:cl:
=> optimize bloom

.github/workflows/autowiki.yml, .github/workflows/ci_suite.yml, .github/workflows/codeowner_reviews.yml, .github/workflows/docker_publish.yml, .github/workflows/gbp.yml, .github/workflows/gbp_collect.yml, .github/workflows/generate_documentation.yml, .github/workflows/update_tgs_dmapi.yml
=> Update Node 12 actions

.github/workflows/ci_suite.yml, .github/workflows/docker_publish.yml, .github/workflows/generate_documentation.yml, .github/workflows/show_screenshot_test_results.yml, code/game/objects/items/eightball.dm, tgui/packages/tgui/sanitize.js, tools/ci/annotate_dm.py, tools/ci/annotate_dm.sh
- https://github.com/tgstation/tgstation/pull/78313
- https://github.com/tgstation/tgstation/pull/78196
- https://github.com/tgstation/tgstation/pull/78225
- https://github.com/tgstation/tgstation/pull/78265
- https://github.com/tgstation/tgstation/pull/78274
- https://github.com/tgstation/tgstation/pull/78291
:cl: MrMelbert
qol: Haunted 8-ball no longer requires the ghost orbit the petitioner to submit votes
qol: Haunted 8-ball ghosts can now change their vote after submitting it
fix: Haunted 8-ball no longer always reports "yes"
fix: Haunted 8-ball no longer always reports default "yes", "no", or "maybe" and now gives a proper eight ball response
fix: Haunted 8-ball can be picked up via the stat panel
/:cl:
=> Random things on my todo list, mostly github related

code/controllers/subsystem/ping.dm
https://file.house/B0ZO.png https://file.house/JRUe.png
NUFC
=> fix ping ss statclick

code/modules/reagents/chemistry/reagents/toxin_reagents.dm, code/modules/reagents/chemistry/recipes/other.dm
:cl:
fix: Unstable Mutagen has a recipe
/:cl:
=> add mutagen recipe

code/_compile_options.dm, code/controllers/configuration/entries/game_options.dm
Forces all ruin budget configs to zero if enabled, preventing generation.
NUFC
:cl:
/:cl:
=> Adds Disable Ruins compile flag

code/game/objects/items/etherealdiscoball.dm
:cl:
fix: The ethereal disco ball no longer screams runtimes
/:cl:
=> fix ethereal discoball

code/__DEFINES/input.dm, code/controllers/subsystem/input.dm
- https://github.com/tgstation/tgstation/pull/71520
:cl: KylerAce
fix: queuing clicks should work correctly now
/:cl:
=> fixes & increases SSinput click delay threshold & moves it and averag

code/datums/emotes.dm, code/game/say.dm, code/modules/mob/mob.dm, tgui/packages/tgui-panel/styles/goon/chat-dark.scss, tgui/packages/tgui-panel/styles/goon/chat-light.scss
:cl:
qol: De-bolded radio channels in chat. Italicized and granted a slightly different color to speaking verbs, to increase readability.
/:cl:
=> Tweaks to chat.

code/modules/projectiles/projectile.dm
=> fixes a bug for real

code/game/objects/effects/decals/cleanable/humans.dm, code/modules/mob/living/brain/brain_item.dm
:cl:
qol: Adjusted the time it takes for blood to try.
fix: Vox now die when debrained.
/:cl:
=> tweak blood decals

code/__DEFINES/dcs/signals/signals_mob/signals_mob_carbon.dm, code/modules/antagonists/heretic/knowledge/blade_lore.dm, code/modules/surgery/bodyparts/dismemberment.dm, code/modules/surgery/bodyparts/stump.dm, code/modules/surgery/bodyparts/wounds/_wounds.dm, code/modules/surgery/bodyparts/wounds/lost_limb.dm, code/modules/surgery/new_surgery/generic_organic.dm, code/modules/surgery/new_surgery/reattach_limb.dm
Brings us closer to bay parity
:cl:
fix: Stumps can be sawed off.
del: An interaction with a heretic path and wounds.
/:cl:
=> Fix stump interactions

code/modules/mob/living/blood.dm
=> fix forensics runtime

.gitignore, _maps/map_files/MetaStation/MetaStation.dmm, code/controllers/subsystem/media.dm, code/controllers/subsystem/ticker.dm, code/game/machinery/dance_machine.dm
:cl:
fix: Media System Validation is less likely to die unexpectedly.
add: The Meta Bar now has a jukebox
add: And it can be used by non-bartenders.
/:cl:
=> Media loading stability improvements

code/modules/tables/tables_racks.dm
Closes #647
:cl:
fix: You can no longer flip operating tables.
/:cl:
=> fix invisible opt table

code/modules/mob/living/carbon/human/human_update_icons.dm
KICKING MYSELF
:cl:
fix: Under certain circumstances, masks would show as invisible in your mask slot. This has been fixed.
/:cl:
=> Fix cases where masks wouldn't show on your HUD

code/game/objects/structures/window.dm
=> fix bad cut_overlay call

code/datums/ai/generic/generic_behaviors.dm
:cl: Time-Green
fix: AI controlled mobs can no longer disembowel or delimb people randomly.
/:cl:
=> Fixes monkeys ripping organs and bodyparts out of other people or themselves

code/controllers/subsystem/events.dm
:cl:
tweak: Changes event bounds from 3-10 minutes to 20-30 minutes.
/:cl:
=> Drastically reduces rate of event occurance

code/modules/grab/grab_living.dm
It was the wrong way round in-game and it was bothering me immensely
=> Fixes text output for grabbing with a full hand

code/game/machinery/dance_machine.dm, code/modules/spatial_grid/cell_tracker.dm, tgui/packages/tgui/interfaces/Jukebox.js
:cl:
qol: The jukebox now works SIGNIFICANTLY better.
/:cl:
=> Jukebox update

code/_onclick/hud/robot.dm, code/_onclick/hud/screen_objects.dm, code/datums/brain_damage/special.dm, code/datums/components/tackle.dm, code/datums/keybinding/mob.dm, code/game/atoms_movable.dm, code/game/machinery/doors/firedoor.dm, code/game/objects/structures/plasticflaps.dm, code/modules/antagonists/cult/cult_items.dm, code/modules/grab/grab_carbon.dm, code/modules/grab/grab_helpers.dm, code/modules/grab/grab_living.dm, code/modules/grab/grab_movable.dm, code/modules/grab/grab_object.dm, code/modules/grab/grabs/grab_passive.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/living_movement.dm, code/modules/mod/modules/modules_supply.dm, code/modules/multiz/movement.dm, code/modules/power/generator.dm
:cl:
fix: Grabs will now properly break when they logically should, no longer requiring a user to perform an action to refresh their state.
fix: Edgelocks are no longer one-way doors.
fix: AI can now close the Thermo-Electric Generator TGUI interface (What a bug!).
fix: Cyborgs and friends can now grab things.
qol: Clicking an item while grabbing it will now end the grab and pickup the item.
/:cl:
=> bugsbugsbugs

_maps/map_files/Theseus/Theseus.dmm, _maps/map_files/Theseus/medbay_holder.dmm, code/game/objects/effects/spawners/random/random.dm, code/game/objects/effects/spawners/random/structure.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/crates.dm, tools/UpdatePaths/unfuck_maint_crates.txt
:cl:
fix: Maintenance crates have items...again? I don't know anymore. This genuinely pissed me the hell off.
fix: Maintenance crates are no longer mapping helper munchers.
/:cl:
=> fixes maintenance crates

code/datums/cinematic.dm, code/modules/unit_tests/create_and_destroy.dm, code/modules/unit_tests/unit_test.dm
no gameplay changes
also, 
- https://github.com/tgstation/tgstation/pull/77504
=> reduce the garbage collection window during CND

code/modules/unit_tests/create_and_destroy.dm
Lets try just making the window a little wider. This must be sleeping proc stuff, right?
=> Increase check queue window during CnD

code/game/objects/structures/memorial.dm
:cl:
qol: Added Delosane900 to the list of Immortals, whose names will live on in git history.
/:cl:
=> Add Delosane900 to the list of immortals

code/modules/unit_tests/create_and_destroy.dm
=> Exempt smart cables from CaD unit testing

code/__DEFINES/combat.dm
:cl:
balance: Crawling is slower.
/:cl:
=> small crawl change

code/modules/mob/living/carbon/inventory.dm
=> REVIEW WHEN NOT DRUNK

code/__DEFINES/_helpers.dm, code/__HELPERS/_lists.dm, code/controllers/subsystem/mapping.dm, code/controllers/subsystem/persistence.dm, code/controllers/subsystem/server_maint.dm, code/controllers/subsystem/vote.dm, code/datums/vote.dm, daedalus.dme, modular_pariah/modules/autotransfer/code/autotransfer.dm
Refactors the awful vote system into datums for extensible behavior.
:cl:
qol: During Crew Transfer votes, non-afk players will be counted as Continue Playing if they do not vote.
fix: Map voting works FOR REAL.
/:cl:
=> Datum Voting

code/__DEFINES/rust_g.dm, code/controllers/subsystem/media.dm, code/controllers/subsystem/ticker.dm
=> rust_g 2.2.0

code/datums/components/construction.dm, code/datums/components/squeak.dm, code/modules/mob/living/carbon/inventory.dm, code/modules/reagents/chemistry/reagents/medicine_reagents.dm
=> Fixes OD warnings

tools/build/build.js, tools/build/lib/byond.js
Port of https://github.com/tgstation/tgstation/pull/80494
:cl:
/:cl:
NUFC
=> Makes build tool use 515 -D argument instead of m.dme file

code/_byond_version_compact.dm, code/controllers/globals.dm, dependencies.sh
I need the scope operator to function right.
=> Bumps MIN_COMPILER_VERSION to 1623

code/controllers/subsystem/vote.dm
:cl:
fix: Votes run their completion code.
/:cl:
=> Makes votes actually do something

code/_byond_version_compact.dm
=> Genericize compat error message

code/controllers/subsystem/input.dm, code/controllers/subsystem/processing/kinesis.dm, code/controllers/subsystem/processing/projectiles.dm, code/controllers/subsystem/throwing.dm, code/controllers/subsystem/verb_manager.dm, code/datums/martial/sleeping_carp.dm, code/game/objects/items.dm, code/game/objects/items/broom.dm, code/game/objects/items/fireaxe.dm, code/game/objects/items/singularityhammer.dm, code/modules/grab/grab_helpers.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/pain.dm
:cl:
fix: Items with unique appearances for being wielded work again.
fix: Throwing processes at the correct rate.
fix: A code error of which it's impact I am unsure of.
/:cl:
=> Small Patch

code/__DEFINES/dcs/signals/signals_mob/signals_mob_living.dm, code/_onclick/click.dm, code/_onclick/hud/hud.dm, code/_onclick/hud/human.dm, code/_onclick/hud/screen_objects.dm, code/datums/progressbar.dm, code/game/objects/items/storage/toolbox.dm
:cl:
qol: Added an on-screen indicator for when you're unable to click.
/:cl:
=> Adds an onscreen click timer

code/controllers/subsystem/ticker.dm
=> Removes a useless stack throw in roundstart logic

code/__DEFINES/_helpers.dm, code/__DEFINES/is_helpers.dm, code/__DEFINES/layers.dm, code/__DEFINES/vv.dm, code/controllers/globals.dm, code/datums/elements/decals/_decal.dm, code/game/turfs/open/floor/fancy_floor.dm, code/modules/admin/view_variables/debug_variables.dm, code/modules/admin/view_variables/topic.dm, code/modules/admin/view_variables/view_variables.dm
closes #807 
:cl:
fix: Neon carpet works again
/:cl:
=> VV ports + fixes neon carpet

.github/workflows/ci_suite.yml, .github/workflows/compile_changelogs.yml, .github/workflows/generate_documentation.yml, .github/workflows/pr_emoji.yml, .github/workflows/round_id_linker.yml, .github/workflows/run_integration_tests.yml, .github/workflows/show_screenshot_test_results.yml, .github/workflows/stale.yml, .github/workflows/update_tgs_dmapi.yml, code/__DEFINES/_profile.dm, code/__DEFINES/rust_g.dm, code/_byond_version_compact.dm, code/controllers/globals.dm, dependencies.sh
515.1630 now required
Updates rustg to 3.1.0
:cl:
server: BYOND 515.1630 is now required to compile.
/:cl:
=> Update Dependencies (BYOND 515.1630, rust_g 3.1.0)

code/modules/clothing/under/skirt_dress.dm, code/modules/mob/living/carbon/carbon_update_icons.dm, code/modules/mob/living/carbon/human/human_update_icons.dm
- https://github.com/tgstation/tgstation/pull/72107
🆑 MrMelbert
fix: Wedding dresses no longer render their shoes over the dress
fix: Things which have inv flags set should more consistently actually hide the things they mean to hide
/:cl:
=> Fixes many instances of item obscurity not working as intended.

code/game/machinery/autolathe.dm, code/game/objects/structures/watercloset.dm, code/modules/antagonists/cult/runes.dm, code/modules/vending/_vending.dm
=> Fixes linter warnings from removing achievements.

code/__DEFINES/lag_switch.dm, code/_globalvars/admin.dm, code/modules/admin/verbs/admingame.dm, code/modules/admin/view_variables/view_variables.dm, html/changelogs/AutoChangeLog-pr-845.yml
nufc, Previous autochangelog edited.
:cl:
/:cl:
=> Lagswitch 845

code/modules/surgery/bodyparts/rendering.dm
These motherfuckers and their "customization" breaking MY server?
:cl:
fix: Vox players with Leg Scutes no longer crash the server.
/:cl:
=> SNOWFLAKE VOX PLAYERS no longer crash the server

code/__HELPERS/cmp.dm, code/controllers/subsystem/codex.dm, code/modules/codex/categories/_codex_category.dm, code/modules/codex/categories/gases.dm, code/modules/codex/categories/reagents.dm, code/modules/codex/categories/surgery.dm, code/modules/codex/categories/uncategorized.dm, code/modules/codex/codex_client.dm, code/modules/codex/entries/_codex_entry.dm, code/modules/codex/entries/machinery.dm, code/modules/codex/entries/mechcomp.dm, code/modules/codex/entries/power.dm, code/modules/codex/entries/tools.dm, code/modules/reagents/chemistry/goon_reagents/medicine_reagents.dm, code/modules/reagents/chemistry/goon_reagents/other_reagents.dm, code/modules/reagents/chemistry/reagents.dm, code/modules/reagents/chemistry/reagents/dispenser_reagents.dm, code/modules/reagents/chemistry/reagents/food_reagents.dm, code/modules/reagents/chemistry/reagents/medicine_reagents.dm, code/modules/reagents/chemistry/reagents/other_reagents.dm, code/modules/reagents/chemistry/reagents/toxin_reagents.dm, code/modules/unit_tests/codex.dm
The codex no longer requires disambiguation (thank god)
:cl:
add: ALL reagents now have a codex entry
/:cl:
=> Ambiguous codex

code/controllers/subsystem/codex.dm, code/modules/codex/categories/reagents.dm, code/modules/codex/codex_client.dm, code/modules/reagents/chemistry/reagents.dm, code/modules/reagents/chemistry/reagents/toxin_reagents.dm, code/modules/reagents/chemistry/recipes/medicine.dm, code/modules/reagents/chemistry/recipes/other.dm
:cl:
balance: Changed plasma vaporization temperature from 323K to 519K (Plasma will ignite at this temperature!)
balance: Reduced heat produced by Dexalin reaction.
fix: Codex searches prioritize results where the query was found in the name again.
qol: Improved readability of reagent codex entries with multiple reactions.
qol: Added plasma ignition temperature to the codex.
/:cl:
=> Adjusts Plasma reactions, fixes codex stuffs

code/_onclick/hud/hud.dm, code/controllers/subsystem/garbage.dm, code/datums/datum.dm, code/game/machinery/camera/camera.dm, code/game/machinery/gulag_teleporter.dm, code/modules/admin/view_variables/reference_tracking.dm, code/modules/unit_tests/find_reference_sanity.dm
- https://github.com/tgstation/tgstation/pull/80443
:cl:
/:cl:
=> Optimize Reftracking

code/modules/modular_computers/file_system/programs/budgetordering.dm
Ports https://github.com/tgstation/tgstation/pull/81950
NUFC
:cl:
/:cl:
=> Fix server hang in budgetordering

code/modules/mob/living/carbon/human/human_defense.dm
=> hotfixitemattack

code/modules/mob/dead/new_player/new_player.dm, html/browser/common.css
:cl:
tweak: Restyled UI buttons.
/:cl:
=> Restyles browser buttons

code/controllers/subsystem/overlays.dm, code/datums/datacore.dm, code/game/objects/items/cards_ids.dm
=> IDs take advantage of 515 technology

interface/interface.dm
:cl:
fix: Updates webmap url
/:cl:
=> WOOPS I DID NOT PUSH THIS (Updates Webmap URL)

code/modules/mob/dead/new_player/new_player.dm
=> Minor latejoin button style fix

code/_onclick/observer.dm, code/modules/mob/dead/observer/observer.dm, code/modules/shuttle/on_move.dm
https://github.com/tgstation/tgstation/pull/82644
=> Remove useless parallax updates

code/modules/three_dsix/living.dm, code/modules/three_dsix/roll.dm, code/modules/three_dsix/stats.dm
=> document some misc code

code/modules/paperwork/paper.dm, tgui/packages/tgui/interfaces/PaperSheet.js
Includes a port of https://github.com/goonstation/goonstation/pull/3808 which is a port of https://github.com/BeeStation/BeeStation-Hornet/pull/2035, with my own additions.
:cl: Kapu1178, PowerfulBacon
fix: Papercode featureset
add: Paper now has a help tab.
/:cl:
=> Fix issue preventing papercode basic html from functioning.

code/game/world.dm
=> re-order tgs reboot

code/modules/antagonists/cult/cult_items.dm, code/modules/mod/mod_link.dm
=> Fix duplicate arguments

code/_onclick/hud/screen_objects.dm, code/game/objects/items.dm, code/modules/mob/inventory.dm
Closes #920
:cl:
fix: Special items like the representation of grabbing can no longer be put into your pocket.
/:cl:
=> fix hand item bug

code/game/turfs/open/space/space.dm, code/modules/atmospherics/ZAS/Turf.dm
:cl:
code: Optimized the process of loading space turfs.
/:cl:
=> optimize space gas

code/__DEFINES/lag_switch.dm, code/__HELPERS/verbs.dm, code/_onclick/hud/ghost.dm, code/_onclick/hud/screen_objects.dm, code/controllers/configuration/entries/general.dm, code/controllers/subsystem/lag_switch.dm, code/modules/client/client_procs.dm, code/modules/client/verbs/ooc.dm, code/modules/discord/discord_helpers.dm, code/modules/discord/discord_sql_functions.dm, code/modules/mob/dead/new_player/login.dm, code/modules/mob/dead/new_player/new_player.dm, code/modules/mob/dead/observer/observer.dm, config/config.txt
:cl:
add: Unverified accounts are no longer instantly kicked, and now sit on the main menu.
tweak: Improved the S O U L menu.
/:cl:
=> Adds a Guest Mode

code/modules/admin/callproc/callproc.dm
- https://github.com/tgstation/tgstation/pull/78924
=> Callproc fix

tgui/public/tgui.html
- https://github.com/tgstation/tgstation/pull/79244
=> opendream TGUI compat

code/__DEFINES/lighting.dm, code/__HELPERS/lighting.dm
- https://github.com/tgstation/tgstation/pull/79117
=> emissive alpha

code/controllers/subsystem/persistent_paintings.dm
- https://github.com/tgstation/tgstation/pull/79495
- https://github.com/tgstation/tgstation/pull/79504
=> cache paintings

tgui/packages/tgui/components/Stack.tsx, tgui/packages/tgui/styles/components/Stack.scss
- https://github.com/tgstation/tgstation/pull/79972
=> Add 'Zebra' display option to Stack components in tgui

code/modules/reagents/chemistry/recipes/pyrotechnics.dm
- https://github.com/tgstation/tgstation/pull/80176
:cl: SyncIt21
fix: Pyrosium now reacts on creation.
/:cl:
=> Pyrosium fix

code/game/turfs/change_turf.dm, code/modules/mapping/mapping_helpers.dm, code/modules/unit_tests/baseturfs.dm
- https://github.com/tgstation/tgstation/pull/79697
=> Cleanup PlaceOnBottom

code/__HELPERS/spatial_info.dm, code/controllers/subsystem/mapping.dm, code/controllers/subsystem/shuttle.dm, code/datums/datum.dm, code/game/atoms.dm, code/game/objects/effects/decals/decal.dm, code/game/turfs/change_turf.dm, code/game/turfs/closed/minerals.dm, code/game/turfs/turf.dm, code/modules/lighting/lighting_atom.dm, code/modules/mob/living/silicon/ai/freelook/cameranet.dm
- https://github.com/tgstation/tgstation/pull/73261
=> Optimizations

code/__DEFINES/atmospherics/atmos_piping.dm
- https://github.com/tgstation/tgstation/pull/13340
:cl:
del: Internals tanks no longer automatically get set to the optimal value.
/:cl:
=> Revert TGstation #13340

code/game/machinery/atm.dm
Makes the ATM put IDs directly into your hand when you eject them. 
I also tried to make cash dispense into your hand but i have no idea how to do that for `spawn_cash_for_amount()`
it was a little odd that it just popped them on the ground before
:cl:
qol: Makes the ATM put IDs directly into your hand when you eject them.
/:cl:
=> Makes the ATM put IDs directly into your hand

code/modules/cargo/packs.dm
Adds the crime scene kit to the forensics crate.
Crime doesn't wait for the PI to arrive on the station.
:cl:
add: Adds the crime scene kit to the forensics crate.
/:cl:
=> Adds the crime scene kit to the forensics crate

code/__HELPERS/turfs.dm, code/datums/cable_click_manager.dm, code/game/objects/effects/cursor_catcher.dm, code/modules/power/cable.dm, daedalus.dme
:cl:
add: Added an Advanced mode to cable coil, enabling the BEST cable placing experience in the known universe. Right Click the floor while holding cable coil to toggle.
/:cl:
=> Advanced cable placement

code/game/objects/items/stacks/overfloor_catwalk.dm
1. closes #1018 
2. Fixes it for every catwalk type I guess
https://github.com/DaedalusDock/daedalusdock/assets/54711687/3a468a06-3ee7-4dee-818e-60b42abcb230
bug bad?
:cl:
fix: You can now place down catwalks again
/:cl:
=> placing down a catwalk actually places down a catwalk

code/game/turfs/open/floor/overfloor_catwalk.dm
:cl:
fix: Catwalks are now anchored.
/:cl:
=> catwalks dont get moved by airflow

code/_onclick/hud/rendering/plane_master.dm
:cl:
fix: Field of View is ACTUALLY black.
/:cl:
=> makes blackness black

code/controllers/subsystem/ambience.dm, code/datums/components/orbiter.dm, code/game/area/areas.dm, code/modules/client/client_defines.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/init_signals.dm, code/modules/mob/logout.dm, code/modules/mob/mob_defines.dm
:cl:
fix: Deaf players can no longer hear ambience.
/:cl:
=> Ambience tweaks again

code/controllers/subsystem/movement/movement.dm
:cl: SmArtkar
fix: Fixed an issue with moveloops.
/:cl:
=> moveloop bug

code/game/atoms.dm, code/modules/detectivework/detective_work.dm, code/modules/three_dsix/stats.dm
=> Small tweak to examine

code/_onclick/hud/hud.dm, code/_onclick/hud/screen_objects.dm, code/game/objects/items/cards_ids.dm, code/modules/mob/mob.dm
:cl:
qol: Improved ID rendering
/:cl:
=> Makes IDs more consistent

code/modules/client/preferences/loadout/loadout_item/backpack.dm, code/modules/client/preferences/loadout/loadout_item/head.dm, code/modules/client/preferences/loadout/loadout_item/shoes.dm, code/modules/client/preferences/loadout/loadout_item/undersuit.dm
adds some items to the loadout shop
namely:
the "swag" uniform and shoes, memes aside I absolutely love the shoes sprite
rollerblades and wheelys, can be bought roundstart so shouldn't be that crazy
skateboard, same as above
delinquent hat, just a neat looking hat
more player customisation should be good?
:cl:
add: the swag set, rollerblades, skateboards, wheelys and delinquent hat to the loadout shop
/:cl:
=> adds some items to the loadout shop

.github/workflows/update_tgs_dmapi.yml
=> Update TGS Auto-Updater

code/__DEFINES/tgs.dm, code/modules/tgs/README.md, code/modules/tgs/core/README.md, code/modules/tgs/core/byond_world_export.dm, code/modules/tgs/core/core.dm, code/modules/tgs/core/datum.dm, code/modules/tgs/includes.dm, code/modules/tgs/v5/api.dm, code/modules/tgs/v5/bridge.dm
This pull request updates the TGS DMAPI to the latest version. Please note any changes that may be breaking or unimplemented in your codebase by checking what changes are in the definitions file: code/__DEFINES/tgs.dm before merging.
Full changelog can be found [here](https://raw.githubusercontent.com/tgstation/tgstation-server/gh-pages/changelog.yml).
- Added consumer APIs for overriding HTTP GET implementation. (https://github.com/tgstation/tgstation-server/pull/1853 @Cyberboss)
- Fixed Discord documentation links. (https://github.com/tgstation/tgstation-server/pull/1853 @Cyberboss)
- Use IETF RFC 2119 wording in documentation. (https://github.com/tgstation/tgstation-server/pull/1853 @Cyberboss)
- Populate some documentation comments for previously undocumented public entities. …
=> Automatic TGS DMAPI Update

_maps/map_files/Theseus/Theseus.dmm
:cl:
fix: Fixes various minor map issues
balance: The Atmospheric SMES unit starts with input and output on.
/:cl:
=> Fixes #1065

code/modules/mob/living/carbon/death.dm, code/modules/mob/living/carbon/life.dm, code/modules/surgery/organs/liver.dm, code/modules/surgery/organs/stomach/_stomach.dm
:cl:
fix: A stomach that dies now properly removes drug effects from drugs present inside.
fix: IPCs don't process reagents.
fix: Not having a liver no longer somewhat breaks your bloodstream.
/:cl:
=> Metabolism Fixes

code/modules/client/client_defines.dm, code/modules/client/client_procs.dm, code/modules/keybindings/bindings_atom.dm, code/modules/keybindings/bindings_client.dm, code/modules/mob/living/living.dm, code/modules/mob/mob_movement.dm, html/changelogs/AutoChangeLog-pr-81464.yml, html/changelogs/AutoChangeLog-pr-85379.yml
https://github.com/tgstation/tgstation/pull/81464
https://github.com/tgstation/tgstation/pull/85379
I'm not copying both of these bodies. Go check yourself.
Manual Changelogs included.
:cl:
/:cl:
=> Ports 2 PRs related to client movement: tg#8146, tg#85379

code/__DEFINES/three_dsix.dm, code/game/alternate_appearance.dm, code/game/objects/items/cigs_lighters.dm, code/game/objects/items/devices/scanners/health_analyzer.dm, code/game/objects/items/storage/medkit.dm, code/modules/grab/grab_datum.dm, code/modules/grab/grab_object.dm, code/modules/grab/grabs/grab_aggressive.dm, code/modules/grab/grabs/grab_neck.dm, code/modules/grab/grabs/grab_strangle.dm, code/modules/mob/living/carbon/human/death.dm, code/modules/mod/modules/modules_medical.dm, code/modules/reagents/withdrawal/generic_addictions.dm, code/modules/vending/medical.dm, code/modules/vending/medical_wall.dm, tools/UpdatePaths/remove_wound_analyzer.txt
:cl:
fix: Added fail-safe code to kill a mob's brain if the body somehow dies.
fix: Added fail-safe code to attempt to prevent lingering grabbed status.
fix: Withdrawal effects are properly removed.
/:cl:
=> 8.15.24 bugs

code/game/turfs/open/space/space.dm, code/modules/lighting/lighting_area.dm
:cl:
fix: Fixed space being unlit in some parts of the map.
/:cl:
=> Starlight Fix IV: A New Hope

tgui/packages/tgui/styles/components/Button.scss
:cl:
fix: Minor visual issue with TGUI buttons.
/:cl:
=> Fix TGUI buttons appearing pressed until another element was focused.

code/_compile_options.dm, code/_onclick/hud/parallax.dm, code/_onclick/hud/screen_objects.dm, code/modules/client/client_defines.dm, code/modules/client/client_procs.dm
- https://github.com/tgstation/tgstation/pull/83395
- https://github.com/tgstation/tgstation/pull/83987
=> Parallax optimizations

code/__DEFINES/maths.dm, code/__HELPERS/combat_helpers.dm, code/game/objects/items.dm, code/modules/flockmind/flock_controller/_flock_controller.dm, code/modules/flockmind/flock_structure/flock_turret.dm
:cl:
fix: Fixed armor penetration not being factored into block chance.
/:cl:
=> 1029204smallbugs

code/__HELPERS/radiation.dm, code/controllers/subsystem/radiation.dm
- https://github.com/tgstation/tgstation/pull/68525
:cl: Pickle-Coding
code: Radiation pulses will ask MC if they should continue processing for every turf they iterate through, rather than just every pulse.
/:cl:
=> fixes radiation performance

code/__DEFINES/rust_g.dm, dependencies.sh
:cl:
server: Bumped rust_g version to 3.5.0
/:cl:
=> bump rust_g to 3.5.0

dependencies.sh
=> rustg 3.5.1

code/modules/mob/living/simple_animal/bot/cleanbot.dm, code/modules/mob/living/simple_animal/bot/firebot.dm, code/modules/mob/living/simple_animal/bot/medbot.dm
Closes #1125
:cl:
fix: Optimized Cleanbots, Firebots, and Medbots.
/:cl:
=> fix bots spamming get_path_to

code/modules/discord/discord_helpers.dm, code/modules/discord/discord_sql_functions.dm
:cl:
fix: The server no longer cries about discord linking if there's no DB.
/:cl:
=> shh, no tears.

code/modules/reagents/chemistry/holder.dm
=> optimize reagnets

code/modules/atmospherics/machinery/components/tank.dm
:cl:
fix: The server is now 0.000000000000001% faster
/:cl:
=> cache an icon

tgui/packages/tgui-panel/styles/goon/chat-dark.scss
:cl:
fix: Removed the text shadow from links using the obvious notice css class.
/:cl:
=> update chat-dark.scss 

code/datums/brain_damage/hypnosis.dm
- https://github.com/tgstation/tgstation/pull/88349
=> Fixes qdel loop in hypnosis destroy()

code/__DEFINES/traits.dm, code/_onclick/click.dm, code/datums/ai/monkey/monkey_behaviors.dm, code/datums/elements/openspace_item_click_handler.dm, code/game/objects/effects/misc.dm, code/modules/antagonists/wizard/equipment/soulstone.dm, code/modules/food_and_drinks/kitchen_machinery/griddle.dm, code/modules/food_and_drinks/kitchen_machinery/oven.dm, code/modules/food_and_drinks/plate.dm
- Remove snowflake trait
- Improve ranged adjacency checks
=> IsReachableBy() code improvements

code/modules/food_and_drinks/plate.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/mob.dm
:cl:
add: You can now smash a plate over someone else's head.
fix: Fixed being unable to point to food on plates.
/:cl:
=> Plate-based combat

_maps/theseus.json, code/datums/map_config.dm, code/modules/unit_tests/__unit_tests.dm, code/modules/unit_tests/_unit_test.dm, code/modules/unit_tests/atmos_moles_tests.dm, code/modules/unit_tests/mapping_standards/__include.dm, code/modules/unit_tests/mapping_standards/_mapping_standards.dm, code/modules/unit_tests/mapping_standards/ladders_must_have_openspace.dm, daedalus.dme
Unit Tests now run a suite of standardized conformance tests. I totally stole this from bay.
map standards good
:cl:
code: There are now special unit tests for enforcing mapping standards.
/:cl:
=> Map Conformance Testing

code/modules/unit_tests/mapping_standards/__include.dm, code/modules/unit_tests/mapping_standards/ladders_must_have_openspace.dm, code/modules/unit_tests/mapping_standards/one_light_per_tile.dm
=> Lights Per Tile MS Test

_maps/RandomRuins/SpaceRuins/bigderelict1.dmm, code/__DEFINES/dcs/signals/signals_mob/signals_mob_living.dm, code/__DEFINES/dcs/signals/signals_movetype.dm, code/__DEFINES/mobs.dm, code/__DEFINES/traits.dm, code/datums/components/clickbox.dm, code/datums/elements/movetype_handler.dm, code/datums/mutations/body.dm, code/game/data_huds.dm, code/game/objects/items/robot/robot_upgrades.dm, code/modules/antagonists/changeling/powers/transform.dm, code/modules/flockmind/flock_mob/flockdrone.dm, code/modules/mob/living/carbon/alien/humanoid/humanoid_update_icons.dm, code/modules/mob/living/carbon/alien/larva/larva_update_icons.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/carbon_defines.dm, code/modules/mob/living/carbon/carbon_update_icons.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/living_update_icons.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/simple_animal/bot/secbot.dm, code/modules/mob/living/simple_animal/friendly/drone/_drone.dm, code/modules/mob/living/simple_animal/guardian/guardian.dm, code/modules/mob/mob.dm, code/modules/mob/mob_update_icons.dm, code/modules/reagents/chemistry/reagents/drink_reagents.dm, code/modules/reagents/chemistry/reagents/other_reagents.dm, code/modules/reagents/chemistry/reagents/toxin_reagents.dm, code/modules/tables/tables_racks.dm
Code from:
- https://github.com/tgstation/tgstation/pull/75892
- https://github.com/tgstation/tgstation/pull/76208
- https://github.com/tgstation/tgstation/pull/86119
:cl:
fix: Huds (ie, the health hud) no longer rotate with the mob they are shown over.
/:cl:
=> Transform code cleanup

code/__DEFINES/robots.dm, code/__HELPERS/paths/jps_path.dm, code/__HELPERS/paths/path.dm, code/game/data_huds.dm, code/game/objects/items/devices/scanners/health_analyzer.dm, code/modules/clothing/suits/armor.dm, code/modules/do_after/do_after.dm, code/modules/mob/living/damage_procs.dm, code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm, code/modules/mob/living/simple_animal/bot/bot.dm, code/modules/mob/living/simple_animal/bot/cleanbot.dm, code/modules/mob/living/simple_animal/bot/ed209bot.dm, code/modules/mob/living/simple_animal/bot/firebot.dm, code/modules/mob/living/simple_animal/bot/floorbot.dm, code/modules/mob/living/simple_animal/bot/honkbot.dm, code/modules/mob/living/simple_animal/bot/hygienebot.dm, code/modules/mob/living/simple_animal/bot/medbot.dm, code/modules/mob/living/simple_animal/bot/mulebot.dm, code/modules/mob/living/simple_animal/bot/secbot.dm, code/modules/mob/mob.dm, code/modules/reagents/chemistry/reagents/medicine_reagents.dm
:cl:
fix: Fixed a deadlock in pathfinding code.
fix: Fixed a hud positioning issue.
fix: Tricordrazine math is no longer insane.
balance: Adjusted Tricordrazine heal ramp-up to compensate.
fix: Medbots now chase their targets for a bit instead of giving up instantly if they moved.
fix: Medbots now re-attempt healing their previously given-up-on target after a specific time period.
balance: Medbots no longer magically heal their target, opting to inject chems instead.
add: Medbots now voice their displeasure if you move out of their range.
/:cl:
=> Bundle o fixes and changes

code/modules/reagents/chemistry/recipes/medicine.dm
:cl:
add: Silver Sulfadiazine now has a byproduct of silicon.
/:cl:
=> Adjusts Silver Sulfadiazine recipe

tgui/packages/tgui/styles/base.scss, tgui/packages/tgui/styles/components/Input.scss, tgui/packages/tgui/styles/components/LabeledList.scss, tgui/packages/tgui/styles/main.scss, tgui/packages/tgui/styles/reset.scss, tgui/packages/tgui/styles/themes/crt.scss, tgui/packages/tgui/styles/themes/crt/crt-blue.scss, tgui/packages/tgui/styles/themes/crt/crt-green.scss, tgui/packages/tgui/styles/themes/crt/crt-yellow.scss, tgui/public/tgui.html
:cl:
tweak: Removed the Nanotrasen logo from TGUI interfaces.
/:cl:
=> Atomize part of tgooey restyle

code/modules/client/preferences/species.dm, code/modules/client/preferences_savefile.dm, code/modules/codex/categories/species.dm, code/modules/mob/living/carbon/human/species.dm, code/modules/mob/living/carbon/human/species_types/ethereal.dm, code/modules/mob/living/carbon/human/species_types/flypeople.dm, code/modules/mob/living/carbon/human/species_types/humans.dm, code/modules/mob/living/carbon/human/species_types/ipc.dm, code/modules/mob/living/carbon/human/species_types/lizardpeople.dm, code/modules/mob/living/carbon/human/species_types/monkeys.dm, code/modules/mob/living/carbon/human/species_types/mothmen.dm, code/modules/mob/living/carbon/human/species_types/shadowpeople.dm, code/modules/mob/living/carbon/human/species_types/skeletons.dm, code/modules/mob/living/carbon/human/species_types/teshari.dm, code/modules/mob/living/carbon/human/species_types/vampire.dm, code/modules/mob/living/carbon/human/species_types/vox.dm, code/modules/mob/living/carbon/human/species_types/zombies.dm
:cl:
add: Added species descriptions for: Human, Jinan, and Vox.
add: Playable species are now in the Codex.
/:cl:
=> Some species descriptions

README.md
Simple git readme link update.
Affects Git, not game. Daedalus is not /tg/Station, so it’s just updating some unnecessarily misdirected old links.
:cl:
config: readme update
/:cl:
=> Git README.md Link Update

.github/workflows/autowiki.yml, .github/workflows/ci_suite.yml, .github/workflows/codeowner_reviews.yml, .github/workflows/compile_changelogs.yml, .github/workflows/docker_publish.yml, .github/workflows/gbp.yml, .github/workflows/gbp_collect.yml, .github/workflows/generate_documentation.yml, .github/workflows/run_integration_tests.yml, .github/workflows/show_screenshot_test_results.yml, .github/workflows/update_tgs_dmapi.yml
Github send email, me fix problem me get email about.
NUFC
:cl:
/:cl:
=> Update CI Node 17 actions to Node 20 (v3 -> v4)

.github/workflows/ci_suite.yml
=> OpenDream Fix

code/modules/grab/grab_living.dm, code/modules/unit_tests/mobswap.dm
:cl:
fix: Fixed another case where grabs would not break correctly.
/:cl:
=> please dont break chain grabs

code/controllers/subsystem/codex.dm
:cl:
fix: Turns out the codex index was ALWAYS regenerated between rounds. Whoops.
/:cl:
=> Allows the codex to be saved across rounds.

tgui/packages/tgui-panel/settings/SettingsPanel.jsx
Number input onDrag sends value, not event,value, therefore using it would set it to undefined. This kills the the ui
Bug fix
Fixes #1191
:cl:
fix: Fixed a bluescreen from setting font size in chat
/:cl:
=> Fixes font size setting

code/datums/station_traits/negative_traits.dm, code/game/atoms_movable.dm, code/game/machinery/hologram.dm, code/modules/flockmind/flock_language.dm, code/modules/language/language_holder.dm, code/modules/language/language_menu.dm, code/modules/mob/living/silicon/pai/pai_defense.dm, code/modules/unit_tests/say.dm
:cl:
fix: Holocalls are now in their intended languages again.
/:cl:
=> Fix holocall languages breaking.

code/__DEFINES/subsystems.dm, code/controllers/subsystem/garbage.dm, code/controllers/subsystem/processing/hydroponics.dm, code/datums/cable_click_manager.dm, code/game/objects/items/stacks/stack.dm, code/game/say.dm, code/modules/detectivework/detective_work.dm, code/modules/economy/account.dm, code/modules/hydroponics/plant_gene_holder.dm, code/modules/language/language.dm, code/modules/language/language_holder.dm, code/modules/language/language_visual.dm, code/modules/modular_computers/file_system/programs/ntmessenger.dm, code/modules/modular_computers/hardware/card_slot.dm, code/modules/research/machinery/_production.dm, code/modules/unit_tests/say.dm
:cl:
fix: Fixed several invisible runtimes.
fix: Fixed talking while being muted resulting in "Makes a strange sound" instead of outright denying speech.
fix: Language-less speech is rendered as an emote.
/:cl:
=> 021025bugs

code/__DEFINES/maps.dm, code/game/gamemodes/blood_plague_outbreak.dm, code/modules/antagonists/vampire/vampire.dm, code/modules/antagonists/vampire/vampire_actions/blood_track.dm, code/modules/antagonists/vampire/vampire_actions/neck_bite.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/shuttle/emergency.dm, code/modules/surgery/bodyparts/wounds/_wounds.dm, code/modules/surgery/bodyparts/wounds/neck_bite.dm, daedalus.dme
:cl:
add: Afflicted - Neck Bite now grants Nutrition and Satiety.
add: Afflicted - Neck Bite is now instant during Bloodlust.
add: Afflicted - Neck Bite now only requires an Aggressive grab during Bloodlust.
add: Afflicted - Neck Bite now heals a small amount of Physical damage.
add: Afflicted - Neck Bite now Mutes the victim for the duration once they have been bit.
add: Afflicted - Blood Hunt now allows you to track any of your previous victims.
/:cl:
=> Vampire Expansion Pack 2

code/__HELPERS/icons.dm, code/datums/actions/mobs/charge.dm, code/modules/mob/living/basic/basic_defense.dm, code/modules/mob/living/simple_animal/animal_defense.dm, code/modules/vehicles/mecha/combat/savannah_ivanov.dm
- https://github.com/tgstation/tgstation/pull/73480
=> https://github.com/tgstation/tgstation/pull/73480

code/_globalvars/bitfields.dm, code/game/objects/items.dm, code/modules/mob/inventory.dm, code/modules/unit_tests/combat/__include.dm, code/modules/unit_tests/combat/combat_quick_equip.dm
Closes #1245 
Closes #1243 
Closes #1242
:cl:
fix: You can no longer equip multiple items to the same slot.
/:cl:
=> Fix equipping

tgui/packages/tgui/interfaces/ChemMaster.jsx
Numberinput does not pass the event
jsx problems
Fixes #1251
:cl:
fix: The chemmaster can have dispatch amounts set again
/:cl:
=> Fixes the chemmaster inputs

code/game/machinery/limbgrower.dm, code/modules/mob/inventory.dm, code/modules/surgery/new_surgery/internal_organs.dm, code/modules/tables/table_flipping.dm
Closes #1257
Closes #1254 
Closes #1255 
Closes #1252
:cl:
fix: The Ore Box now works again.
fix: The Limbgrower now works again.
fix: Flipping tables no longer moves anchored objects.
fix: Repair Internal Organ surgery can be completed.
/:cl:
=> 03/17/25 Downstream Bugs

code/modules/client/client_procs.dm, html/statbrowser.css, html/statbrowser.js, tgui/packages/tgui/layouts/Layout.jsx, tgui/packages/tgui/styles/layouts/Layout.scss, tgui/packages/tgui/styles/main.scss
* https://github.com/tgstation/tgstation/pull/88617/
Enables devtools, fixes scrollbars
=> adds devtools, fixes scrollbars

code/modules/tgui_panel/external.dm, interface/skin.dmf, tgui/packages/tgui-panel/index.jsx
- https://github.com/tgstation/tgstation/pull/88663
=> fixes chat zfighting on 516

tgui/public/tgui.html
- https://github.com/tgstation/tgstation/pull/89956
=> Fixes asset loading

code/__HELPERS/text.dm, code/modules/tgui/tgui_input_list.dm, code/modules/tgui/tgui_input_text.dm, tgui/packages/tgui/interfaces/TextInputModal.tsx
- https://github.com/tgstation/tgstation/pull/90039
=> TGUI input text cleanup

code/modules/jobs/job_types/acolyte.dm, code/modules/jobs/job_types/augur.dm, code/modules/jobs/job_types/paramedic.dm
:cl:
add: Aether members spawn with a diagnosis book in their backpack.
/:cl:
=> aether members spawn with the diagnosis book

code/modules/client/client_procs.dm, tgui/global.d.ts, tgui/packages/common/storage.ts
- https://github.com/tgstation/tgstation/pull/88624
=> implement ByondStorage

tgui/public/tgui.html
- https://github.com/tgstation/tgstation/pull/90256
=> CORS issues

code/modules/mob/living/carbon/carbon_health.dm, code/modules/mob/living/carbon/human/examine.dm
=> Fix master

code/game/objects/items/devices/scanners/health_analyzer.dm, code/game/objects/items/diagnosis_book/diagnosis_conditions.dm, code/game/objects/items/diagnosis_book/diagnosis_symptoms/brain_activity_symptoms.dm, code/game/objects/items/diagnosis_book/diagnosis_symptoms/circulation_symptoms.dm, code/game/objects/items/diagnosis_book/diagnosis_symptoms/gi_symptoms.dm, code/game/objects/items/diagnosis_book/diagnosis_symptoms/skin_symptoms.dm, code/game/objects/items/grenades/chem_grenade.dm, code/game/objects/items/storage/boxes.dm, code/modules/mob/living/blood.dm, code/modules/mob/living/carbon/carbon_health.dm, code/modules/surgery/bodyparts/_bodyparts.dm, code/modules/surgery/bodyparts/bodypart_examine.dm
:cl:
add: Updated the Inspect Limb grab function, it now tells you more information.
/:cl:
=> Diagnosis additions

code/datums/browser.dm, code/modules/mob/dead/new_player/new_player_panel.dm, html/browser/playeroptions.css
:cl:
fix: The latejoin menu renders correctly.
/:cl:
=> Fix latejoin menu

_maps/map_files/Theseus/Theseus.dmm
Restyles dormitories/fitness to fit the colony aesthetic better. Removes the holodeck on account of how out of place it is in our setting.
<details>
<summary><i>(Examples of the tweaked areas.)</i></summary>
_Outdated video example took during testing._
https://youtu.be/wIi1M0qqyWs
_New dormitories look!_
_Private Investigator's Office tweaked, too._
_De-soulification of the Medbay Lobby._
</details>
Fixes several mapping errors across the map.
<details>
<summary>Fixes issue #835.</summary>
</details>
<details>
<summary>Fixes issue #876.</summary>
</details>
Aligns the map to fit our intended aesthetic better. Fixes several issues with the map.
:cl:
add: New dormitories design! Medical's lobby and the PI's office have also been tweaked.
del: Removes the holodeck from Theseus on account of …
=> Dormitories Restyling + Map Fixes

_maps/map_files/Theseus/Theseus.dmm, code/modules/admin/verbs/mapping.dm
Single-access airlocks were done, multi-access airlocks left untouched for now.
=> Converts most of Theseus airlocks to access helpers

code/__HELPERS/game.dm, code/datums/storage/storage.dm, code/game/machinery/atm.dm, code/game/machinery/datanet/p2p_phones/_p2p_phones.dm, code/game/machinery/doors/door.dm, code/game/machinery/firealarm.dm, code/game/objects/items.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/extinguisher.dm, code/modules/atmospherics/machinery/airalarm.dm, code/modules/power/apc/apc_main.dm, code/modules/recycling/disposal/bin.dm, code/modules/tables/tables_racks.dm, code/modules/vending/_vending.dm
:cl:
add: Added interaction animations to many common interactions.
/:cl:
=> 050225moreinteractions

code/modules/tgui/tgui_alert.dm
:cl:
fix: Fixed a hard del.
/:cl:
=> tgui modal harddel fix

tgui/packages/tgui-panel/chat/renderer.jsx, tgui/packages/tgui-panel/panelFocus.ts
- https://github.com/tgstation/tgstation/pull/90336
=> Fix chat auto scrolling (i hope)

code/__HELPERS/_lists.dm, code/controllers/subsystem/economy.dm, code/game/machinery/computer/security.dm, code/modules/jobs/job_types/_job.dm
:cl:
fix: Fixed a rare bug that caused people to not get paid.
/:cl:
=> fixes payday runtime

tgui/.swcrc
Swc started hosting their own https://swc.rs/docs/configuration/swcrc
minor bug fix
=> [tgui] Fixes swcrc json schema

code/datums/status_effects/drug_effects.dm, code/datums/status_effects/skill_modifiers/positive.dm, code/modules/power/supermatter/nupermatter.dm, code/modules/projectiles/guns/ballistic/revolver.dm
:cl:
add: More disco flavor interactions.
/:cl:
=> more disco

code/controllers/configuration/entries/general.dm, code/modules/client/client_procs.dm, code/modules/client/preferences/auto_fit_viewport.dm, code/modules/client/verbs/ooc.dm, config/config.txt
The CID randomizer check has not worked in literally like 10 years
=> Removes CID randomizer check, removes a sleep in client/New

code/__DEFINES/time.dm, code/__HELPERS/time.dm, code/game/objects/items/manuals.dm, code/game/objects/items/stacks/cash.dm, code/modules/computer4/data/terminal/medtrak/medtrak_comment_commands.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/reagents/reagent_containers/cups/glassbottle.dm
:cl:
tweak: Adjusted the in-game year.
/:cl:
=> Adjust in-game year

code/game/objects/items/stacks/cash.dm
fedaration mark
Bro is at work
:cl:
spellcheck: fedaration -> Federation
/:cl:
=> fedaration mark

code/modules/admin/verbs/debug.dm, code/modules/admin/verbs/secrets.dm, code/modules/client/verbs/ooc.dm, code/modules/library/book.dm
fixes #1239 
Went through every browse call and fixed those that were serving bad HTML. Everything I haven't changed *should* be serving proper HTML.
=> [516] Fixes bad HTML browse() calls

tgui/package.json, tgui/webpack.config.js, tgui/yarn.lock
Closes #1300
:cl:
fix: Fixed TGUI assets such as cursors not working.
/:cl:
=> Fixes TGUI asset inlining

code/game/objects/items/crayons.dm, code/modules/aether/chalk.dm
what it says on the tin, chalk is now edible and crayons are edible (again)
I like the idea of being handed chalk to do a magical ritual and and just eating it instead
:cl:
add: Chalk is now edible
fix: Crayons are now edible again
/:cl:
=> makes chalk and crayon edible

code/modules/surgery/machines/bodyscanner.dm
:cl:
add: The Bodyscanner now has a print function.
/:cl:
=> add print button to bodyscanner

code/datums/mergers/_merger.dm, code/game/objects/effects/wanted_poster.dm, code/modules/power/singularity/field_generator.dm
Why does byond even allow this.
:cl:
/:cl:
=> Fix dreamchecker errors

code/__DEFINES/mobs.dm, code/game/objects/structures/memorial.dm
:cl:
add: PWNRA aka Gramps added to the memorial list.
fix: A small error in attack code handling.
/:cl:
=> Small tweaks

code/game/objects/items/melee/baton.dm
:cl:
fix: Batons have an attack cooldown again.
/:cl:
=> fix batong
