- code/_onclick/click.dm
- code/game/objects/structures/low_wall.dm
:cl:
fix: Low walls can now be painted while a window is atop them.
/:cl:
> Fix low walls being unpaintable while a window was on them

- code/modules/mob/mob_movement.dm
- code/modules/mod/mod_ai.dm
Returns diagonal movement to `2` instead of `sqrt(2)`
It was always supposed to be this way.
It makes combat less "run around like a headless chicken", and makes more sense for a grid-based game.
:cl:
balance: Diagonal movement is slower than orthogonal movement
/:cl:
> Returns diagonal movement to Manhatten distance

- code/__DEFINES/atmospherics/ZAS.dm
- code/controllers/subsystem/zas.dm
- code/game/machinery/doors/firedoor.dm
- code/modules/atmospherics/ZAS/Zone.dm
See code comment for details.
:cl:
fix: Some oddities with ZAS fixed. Notably on Metastation.
/:cl:
> Fixes a gamebreaking zas init bug

- code/controllers/subsystem/credits.dm
Changes a couple uses global mob lists to simply `SSticker.minds`. Greatly improves code quality, as well as adds support for multiple mobs per ckey in the credits.
:cl:
add: Credits now display all characters a player inhabited during the round.
add: Credits now display gibbed characters as dead.
/:cl:
> Improves SScredits code

- code/game/area/areas.dm
This is a 3 line code-removal that just makes it so lights aren't randomly disabled 4no raisin at roundstart. 
It's kinda annoying behavior and it doesn't even turn the switches off as best I can tell, just the lights, so it's a glitch.
:cl:
fix: Lights are no longer randomly off at roundstart, for no reason. 
/:cl:
> Removes randomly disabled lighting

- code/modules/atmospherics/ZAS/Diagnostic.dm
- code/modules/atmospherics/ZAS/Turf.dm
- code/modules/atmospherics/ZAS/XGM/xgm_gas_mixture.dm
- code/modules/mob/living/simple_animal/hostile/tree.dm
- code/modules/reagents/chemistry/reagents/food_reagents.dm
- code/modules/reagents/chemistry/reagents/other_reagents.dm
- code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
https://user-images.githubusercontent.com/75460809/197423101-b7db8c8d-18c3-4733-8515-f20158bf22db.mp4
:cl:
fix: Unsimulated turfs can no longer have their gas mutated.
/:cl:
> Fixes ZAS (again) (again) (again)

- _maps/map_files/KiloStation/KiloStation.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/PubbyStation/PubbyStation.dmm
- code/controllers/subsystem/ticker.dm
- code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
- code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
- code/modules/mob/dead/new_player/new_player.dm
Fixes the "Observe" button on the new player panel not actually auto-observing on round start.
Using a Multitool on a vent scrubber or pump will toggle it's ability to sleep.
:cl:
add: Using a multitool on a vent scrubber/pump toggles it's ability to sleep.
fix: "Observe" on the New Player Panel will now auto-observe on roundstart.
/:cl:
> Fixes "Observe Ready" and adds a multitool interaction to vent scrubbers/pumps.

- code/game/atoms_movable.dm
- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
- code/game/machinery/doors/windowdoor.dm
- code/game/machinery/shieldgen.dm
- code/game/objects/effects/effect_system/effects_foam.dm
- code/game/objects/structures/false_walls.dm
- code/game/objects/structures/holosign.dm
- code/game/objects/structures/mineral_doors.dm
- code/game/objects/structures/windoor_assembly.dm
- code/game/objects/structures/window.dm
- code/modules/antagonists/blob/structures/_blob.dm
- code/modules/atmospherics/ZAS/Atom.dm
- code/modules/atmospherics/ZAS/Turf.dm
- code/modules/atmospherics/ZAS/zas_extras/inflatable.dm
- code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
Any turf that
- Has no air mixture (this should never happen but you never know)
- Has a `total_moles` count of `0`
is treated as a total vacuum for the purposes of heat exchanging pipes.
All spacestation cold loops will behave the same, and putting HE pipes on plating will no longer tank their usefulness.
:cl:
fix: Heat exchanging pipes are more consistent. Affecting primarily cold loops in space.
fix: Windows will now trigger ZAS updates when anchored or unanchored.
/:cl:
> Vacuums now all act like space for heat exchange

- code/game/objects/items/mail.dm
Removes OOC restriction preventing anyone from opening mail, which is an IC action. In game law can be updated to add this as a charge if it isn't already
gives ne'er-do-wells more opportunity to cause trouble and emergent gameplay™
:cl:
tweak: Letters can now be opened by anyone, not just the recipient.
/:cl:
> The mail is free

- code/game/area/areas.dm
- code/modules/atmospherics/machinery/airalarm.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/power/lighting/light.dm
title
:cl:
fix: "Contaminated" on air alarms no longer siphons out N2/O2
fix: Humans are now area sensitive regardless of mood config.
/:cl:
> Fixes the contaminated setting on air alarms

- code/modules/mob/living/carbon/human/examine.dm
:cl:
code: human examine no longer runtimes
/:cl:
> fixes examine runtime related to mood

- code/__DEFINES/construction.dm
- code/game/objects/structures/window.dm
Melee armor on reinforced windows is changed from 80 to 30. Have you ever noticed that regular reinforced glass is _really_ hard to break? That's because it shared the same armor values with plasma glass!
For an example of how this will affect breaking windows, let's look at how many hits from a wielded spear a reinforced window can take.
- With the changes in this PR: 12 hits to break a window.
- In normal gameplay: **42 CONSECUTIVE HITS**
This will also allow weaker mobs like space carp to break r-windows again. This is arguably a good change, because it means more people will get killed by space wind.
Deconstructing and constructing windows has been made faster and now has less steps, and no longer is a right-click action. Constructing R-windows now goes screwdriver (anchoring) -> …
> (BALANCE CHANGE) Nerfs Reinforced Glass melee armor

- code/__HELPERS/spatial_info.dm
- code/datums/brain_damage/imaginary_friend.dm
- code/datums/chatmessage.dm
- code/game/atoms.dm
- code/game/machinery/doors/passworddoor.dm
- code/game/machinery/hologram.dm
- code/game/machinery/telecomms/broadcasting.dm
- code/game/objects/items.dm
- code/game/objects/items/devices/radio/intercom.dm
- code/game/objects/items/devices/radio/radio.dm
- code/game/objects/items/devices/taperecorder.dm
- code/game/objects/items/eightball.dm
- code/game/say.dm
- code/modules/antagonists/disease/disease_mob.dm
- code/modules/antagonists/gang/cellphone.dm
- code/modules/assembly/voice.dm
- code/modules/mob/dead/observer/observer_say.dm
- code/modules/mob/living/carbon/human/species_types/dullahan.dm
- code/modules/mob/living/living_say.dm
- code/modules/mob/living/silicon/ai/freelook/eye.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
- code/modules/mob/living/simple_animal/parrot.dm
- code/modules/mob/living/simple_animal/slime/slime_say.dm
- code/modules/wiremod/components/atom/hear.dm
Adds a `sound_loc` var to `create_chat_message()` and `Hear()`. This can be set to define an atom that is actually emitting the sound, which is where runechat will display. 
closes #103 
:cl:
add: Runechat now displays over intercoms and non-held radios.
tweak: Intercoms are now OFF by default.
/:cl:
> [Experimental] speaker_location()

- code/__DEFINES/flags.dm
- code/_onclick/adjacent.dm
- code/game/machinery/_machinery.dm
- code/game/objects/structures/crates_lockers/closets.dm
In layman's terms, you can grab this wrench now.
Code wise: Adds a new `pass_flags_self` flag called `LETPASSCLICKS` that lets you mark an atom to not block `ClickCross()` attempts.
:cl:
add: Lockers, crates, and machines no longer block click attempts in adjacency checks. Basically, you can reach tables cornered between lockers/machines.
/:cl:
> You can now reach over machinery/lockers.

- _maps/map_files/Atlas/atlas.dmm
not sure if I made this PR right, if it's done wrong let me know.
This includes atmos, engineering with the SM and storage, and every science area except for robotics. everything has been added except for lighting, since the lighting changes are still being tested.
Previews:
<details>
<summary>Engineering</summary>
<br>
</details>
<details>
<summary>Atmospherics</summary>
<br>
</details>
</details>
<details>
<summary>Science</summary>
<br>
</details>
</details>
<details>
<summary>Starboard Solars</summary>
<br>
> Add Engineering, Atmospherics, Science, and Starboard Solars to the Atlas

- code/__DEFINES/dcs/signals/signals_atom/signals_atom_movement.dm
- code/game/atoms.dm
Adds a signal that is sent when atom changes its density.
Another useful signal, it's required for one of the components I made for https://github.com/DS-13-Dev-Team/Daedalus_Dock and I don't want to deal with conflicts later.
:cl:
code: Added signal that is sent when atom changes density
/:cl:
> Adds a signal on atom density change

- .github/workflows/compile_changelogs.yml
- .github/workflows/make_changelogs.yml
- .github/workflows/update_tgs_dmapi.yml
No code changes so no CL, allows the repo secret `DD_BOT_PAT` to be set to bypass protected branch checks.
~~The role system is one of github's more obnoxious paid features...~~
> Update workflows for protected branches

- tgui/packages/tgui-panel/chat/renderer.js
:cl:
tweak: Text stacking now adds (n) to the font size, instead of (2n).
tweak: Text stacking is now whitelisted to local chat & combat text.
/:cl:
> Adjustments to text stacking

- tgui/packages/tgui/index.js
- tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
- tgui/packages/tgui/styles/base.scss
- tgui/packages/tgui/styles/themes/rounded_base.scss
The preference menu by opinion looks weird with this,
so it's excluded from this change.
(most) TGUI elements no longer round off their edges.
Looks better in my opinion.
:cl:
imageadd: TGUI interfaces have had their corners un-cut.
/:cl:
> TGUI corners are now sharp by default

- code/modules/interaction_particle/interaction_particle.dm
Stops the mouse pointer from seeing the interaction hand effect (and by extension, it appearing in the right click menu)
You shouldn't see this.
:cl:
fix: Interaction hand icon will no longer be visible in the right click menu
/:cl:
> Fix mouse pointer over interaction particles 

- code/__HELPERS/spatial_info.dm
- code/datums/chatmessage.dm
- code/game/atoms.dm
- code/game/machinery/bank_machine.dm
- code/game/machinery/computer/chef_orders/chef_order.dm
- code/game/objects/items/devices/radio/radio.dm
- code/game/objects/structures/traps.dm
- code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/simple_animal/bot/bot.dm
adds `hear_location()` which by default points to `src`. Observers are `orbit_target || src`. Practical change is in the title.
:cl:
fix: Observers no longer get runechat for the radio of their orbit target
/:cl:
> Observers no longer get runechat for the radio of their orbit target

- code/_onclick/hud/human.dm
- code/datums/outfit.dm
:cl:
fix: The "Rest" and "Pull" HUD icons no longer lie to users if they logged in after the mob starting resting or pulling.
fix: SSwardrobe will now delete held items it fails to equip.
fix: Vox no longer have a permanent N2 tank embedded inside them.
/:cl:
> Fixes huds & SSwardrobe bug

- code/_onclick/hud/rendering/render_plate.dm
Names are unique.
:cl:
fix: Gravity pulses have had their distortion effect restored.
/:cl:
> Fixes the Gravity Pulse plane not having it's displacement map

- code/modules/vehicles/mecha/equipment/mecha_equipment.dm
- code/modules/vehicles/mecha/equipment/tools/medical_tools.dm
- code/modules/vehicles/mecha/mecha_actions.dm
:cl:
fix: Various mech interactions now work again
/:cl:
> do_after() fixes

- code/modules/asset_cache/asset_list.dm
The asset was being loaded, seeing that fully_generated is false, so it attempts to rebuild. The rebuilding clears the existing file cache, and fucks us.
- https://github.com/tgstation/tgstation/pull/69852
:cl:
fix: Character Creator icons will not longer appear invisible during some rounds.
/:cl:
> Fixes asset caching

- code/modules/vehicles/mecha/_mecha.dm
- code/modules/vehicles/sealed.dm
:cl:
fix: You can enter vehicles again.
/:cl:
> Fixes more do_after() issues

- code/modules/antagonists/heretic/heretic_antag.dm
:cl:
fix: Heretics can draw their rune again
/:cl:
> fix heretic draw_rune

- code/modules/cargo/supplypod.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/human/species_types/plasmamen.dm
- code/modules/mob/living/carbon/human/species_types/vox.dm
- code/modules/reagents/chemistry/recipes/medicine.dm
- code/modules/surgery/organs/tongue.dm
:cl:
fix: Kidnapped Vox and Plasmamen spawn with their proper equipment
fix: Tongueless players
fix: Oculine's explosion thingy happens properly.
/:cl:
> Miscellaneous issues

- code/_onclick/hud/rendering/plane_master.dm
:cl:
fix: Emissives and Movable Lights no longer "poke holes" in Bloom.
/:cl:
> Movable lights no longer poke holes in the Additive Lighting plane

- code/controllers/subsystem/explosions.dm
fixes the Qdeleted thing being thrown around. runtimes spamming the shit out of the logs
- https://github.com/tgstation/tgstation/pull/69604
:cl: ShizCalev
fix: Explosions don't cause runtimes anymore. Atleast not as many. I'd insert a trolleybus emote here but the emoji stripper will remove it.
/:cl:
> fixes qdeling atoms being thrown by explosions

- code/controllers/master.dm
- code/controllers/subsystem.dm
- https://github.com/tgstation/tgstation/pull/72324
The mc now keeps track of how many times a subsystem has slept in fire()
The mc now keeps track of how many times a subsystem has slept in fire()
:cl: MrStonedOne
code: The mc now keeps track of how many times a subsystem has slept in fire()
/:cl:
> The mc now keeps track of how many times a subsystem has slept in fire()

- code/modules/mob/dead/new_player/new_player.dm
Adds a verb to bypass observer checks and spawn you in immediately as an observer.
Requires `R_DEBUG`
You should know what you're doing if you're doing this.
I want it, eat shit.
:cl:
qol: Developers can bypass observer checks to watch map generation
/:cl:
> New player verb to immediately bypass observer checks

- tgui/packages/tgui/styles/base.scss
Significantly brightens the base TGUI theme, Up to community opinion on this one.
New (v2)
New (v1)
Old
:cl:
imageadd: TGUI's base theme has been significantly brightened
/:cl:
> Base TGUI theme brightening

- code/modules/antagonists/revenant/revenant_abilities.dm
:cl:
fix: Revenant can drain souls again.
/:cl:
> Fix revenant do_afters

- code/modules/surgery/bodyparts/_bodyparts.dm
- code/modules/surgery/bodyparts/injuries.dm
:cl:
fix: You will no longer scream repeatedly when taking many small ticks of damage.
/:cl:
> Removes soul from bodypart code

- code/controllers/configuration/entries/general.dm
- code/controllers/subsystem/ticker.dm
- config/config.txt
:cl:
config: Server owners can now staple text to the new round notice
del: This removes an already unused config entry that was intended to serve the same purpose, CHAT_NEW_GAME_NOTIFICATIONS
/:cl:
> Generalized staple to newgame pings

- code/game/machinery/camera/presets.dm
Fixes #233
I am really genuinely surprised that this issue hasn't been caught yet.
:cl:
fix: Autoname cameras can now be selected properly
/:cl:
> m' proper~

- code/__DEFINES/mobs.dm
- code/__DEFINES/stat.dm
- code/datums/diseases/advance/symptoms/heal.dm
- code/modules/mob/living/blood.dm
- code/modules/mob/living/carbon/carbon_movement.dm
- code/modules/surgery/organs/stomach/_stomach.dm
:cl:
balance: Hunger decays at a rate of 0.04/s (up from 0.01)
balance: Satiation decays at a rate of 0.2/s (before: 1/s). This means being fully satiated will last 25 minutes.
/:cl:
> More hunger stuff

- code/datums/mutations/body.dm
- code/game/objects/items/dna_injector.dm
Changes all in-game references of "spastic" to spasms. More so a slur within the UK but it's an eyebrow raising one to put it lightly.
Should be noted that the status effect and brain traumas that do this/something similar opt to use spasms instead so it's only genetics that refers to it, so it also makes it more in line with the rest of the nomenclature
> Changes spastic to (muscle) spasms

- code/_onclick/hud/pai.dm
- code/game/objects/items/devices/scanners/health_analyzer.dm
- code/modules/detectivework/scanner.dm
Removes an utterly baffling usage of rightclick on health analyzers.
Right click shouldn't be used as any other free keybind.
:cl:
qol: the Health Analyzer chem scanner has been readded to the mode cycle loop.
/:cl:
> Health Analyzer chem scanner rightclick purge

- code/modules/power/lighting/light.dm
Intact lights can now be broken using force, instead of putting the item into the bulb socket.
I don't know when this check was removed (presumably by accident) but now it's back.
:cl:
fix: Fixed light fixtures having incorrect attack behavior
/:cl:
> Fixes light fixture attacking

- code/game/objects/effects/contraband.dm
- code/game/objects/effects/wanted_poster.dm
- code/game/turfs/closed/walls.dm
Ports https://github.com/tgstation/tgstation/pull/69956 by ShizCalev
contraband.dm hasn't been included (although it has some related code) yet, it's 3AM and I'd need to go over it in better detail to port what's relevant due to files being different.
Currently the PR seems to fix https://github.com/DaedalusDock/daedalusdock/issues/188 as shown here:
:cl: ShizCalev
fix: Wanted/missing posters are no longer broken.
fix: Telekinesis no longer teleports removed posters
/:cl:
> Port of /tg/'s wanted poster fix

- code/modules/mob/living/blood.dm
Fix missing punctuation in the bleeding message by adding punctuation if no rate of change is set.
It annoyed me.
> Fix missing punctuation in bleeding message

- code/modules/power/lighting/light.dm
- code/modules/power/lighting/light_mapping_helpers.dm
- modular_pariah/modules/aesthetics/lights/code/lighting.dm
This really only affects coders.
:cl:
Fix: Lighting no longer has a massive delay on actually setting up lights.
/:cl:
> Lighting actually initializes during init

- code/__DEFINES/atmospherics/atmos_canpass.dm
:cl:
qol: The station holds air again.
fix: The station holds air again.
/:cl:
> Fixes Multi-ZAS.

- code/controllers/configuration/entries/general.dm
- code/game/turfs/closed/walls.dm
- code/game/world.dm
- config/config.txt
:cl:
fix: Server hub entry will no longer be cut short
/:cl:
> Fix wall icons in mapmaking tools & hub entry length

- code/controllers/subsystem/nightshift.dm
:cl:
fix: Raising the security level to blue will no longer sometimes start nightshifts
/:cl:
> security level raise fix

- code/game/objects/items.dm
- code/modules/interaction_particle/interaction_particle.dm
- code/modules/mob/living/carbon/carbon.dm
:cl:
fix: Item Attack Animations work again.
/:cl:
> Fix Attack Animations

- code/modules/asset_cache/assets/bibles.dm
315 fucking icon states
goddamnit it lemon boy what the fuck were you thinking
:cl:
imagedel: prevents nearly 300 icon states from getting built and pushed to clients. You probably won't care about this.
/:cl:
> I hate asset code

- code/controllers/configuration/entries/game_options.dm
- code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
- config/game_options.txt
Will reenable on config reload
Allows the disk security system to be safely disabled and reenabled via config.
Lowpop nag, and the way this works is so cheap it doesn't really matter.
:cl:
config: Lone Op disk security nagging can now be configured.
/:cl:
> Allow lone op disk nag to be disabled

- code/modules/mob/living/simple_animal/hostile/mining_mobs/mining_mobs.dm
Did you know? Lavaland mobs only take one third of damage dealt by most projectiles or throwing weapons. This is to prevent players from using creative methods of killing mobs in a sandbox game. This PR removes the damage reduction, but keeps the AI aggroing on anyone that shoots at them.
Off-station mobs shouldn't be balanced by forcing you to use one specific weapon, it discourages shaft miners from getting help from other departments or having security try to rescue dead miners. I have yet to hear anyone say that they *like* only being able to use a KA to kill things, either.
:cl:
balance: Lavaland mobs no longer take reduced projectile or throwing damage.
/:cl:
> Removes lavaland mob gun/thrown damage reduction (balance change)

- code/modules/vehicles/trolley.dm
local paraplegic player complains trolley is too focused on movement to be usable
> Trolleys can be rotated on altclick

- code/modules/mob/living/carbon/human/species.dm
- code/modules/surgery/bodyparts/dismemberment.dm
- code/modules/surgery/bodyparts/head.dm
:cl:
fix: Transformations no longer ghost players.
fix: Changing bodytypes updates clothing to reflect new body.
/:cl:
> Fix Transformations ghosting the user and minor sprite issue.

- code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
:cl:
fix: TEG circulators no longer lock up if the output network is empty.
/:cl:
> Fix circulators getting "stuck" if the output was a vacuum.

- code/__DEFINES/mobs.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/carbon_defense.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/surgery/organs/lungs.dm
:cl:
balance: Passout threshold from oxyloss from 50 to 100
balance: Oxyloss taken when failing a breath from 3 to rand(2, 4)
balance: Oxyloss taken when failing a breath in critical condition from 3.3 to rand(3,6)
/:cl:
> rebalance softcrit/oxyloss

- code/__DEFINES/stat.dm
- code/modules/client/verbs/suicide.dm
- code/modules/mob/living/basic/health_adjustment.dm
- code/modules/mob/living/damage_procs.dm
- code/modules/mob/living/simple_animal/damage_procs.dm
- code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
- code/modules/unit_tests/combat.dm
- code/modules/vehicles/mecha/equipment/tools/mining_tools.dm
Currently, values like oxyloss and toxloss, are clamped at mob.maxHealth * 2. This works perfectly fine on TG, if your mob max HP is exactly 100. Why is that? Well, TG's death point is -100. 100 * 2 = 200 which is also the difference between maxHealth and HEALTH_THRESHHOLD_DEAD.
But, what if your mob has more than 100 max hp? Well, then shit starts to kind of break. 
If your mob has 500 hp, you can take a 400 tox/oxy damage past the point of death.
If your mob has 1000 hp, you can take 900 tox/oxy damage past the point of death.
This sounds fine on paper, until you realise that it scales exponentially, and the default mobs like players don't take any damage past the point of death.
:cl:
fix: You can now die from only one damage type again.
/:cl:
> Fix bug with damage

- code/modules/assembly/flash.dm
:cl:
fix: Fixed AoE flash function
balance: AoE flash now has a cooldown.
/:cl:
> Fix AoE flash not applying stamina damage

- code/datums/actions/action.dm
:cl:
fix: Action Buttons that require consciousness can now be used in Soft Crit
/:cl:
> fix action button feedback

- code/datums/components/engraved.dm
:cl:
qol: Wall engravings can now be removed with a welding tool.
/:cl:
> make engravings removable with a welder

- code/__HELPERS/spatial_info.dm
One of the hottest procs in the game. The way it works is it uses the spatial grid to grab all hearers in a given range. Then, it assigns mobs called ears to every turf that contains a hearer. Then, it uses view() to determine who should actually hear the message based on sight. 
There's a pretty simple optimization here, given to us by Dantom back in the dark ages. `hearers()`. `hearers()` is a *very* fast proc that returns all mobs in view, ignoring darkness. We can't replace Ears with this entirely, because SS13/TGMC have objects that need to be aware of hearing, like Radios. But this is still a massive improvement.
Benchmarked using Lohikar's closed-source benchmarking tools. Left-to-right:  Average Iterations, Harmonic Average Iterations, Standard Deviation, Standard Deviation As …
> Optimize get_hearers_in_view()

- code/game/objects/structures/railings.dm
https://github.com/tgstation/tgstation/pull/70588
Kapu want
:cl: BrDown
fix: Deconstructing a railing will now give the proper amount of iron rods.
/:cl:
> Makes the railings drop the same amount of rods as used

- code/modules/client/preferences/augments/_augment.dm
- code/modules/client/preferences/augments/augments.dm
- code/modules/research/machinery/_production.dm
:cl:
fix: Fixed a couple issues with augments/implants.
fix: Fabricator icons update properly.
/:cl:
> Augment bugs

- code/modules/mob/camera/camera.dm
Fixes camera Z moving
Camera mobs can move up and down without issues once again
:cl:
fix: fixed camera not being able to move between Z levels
/:cl:
> Fixes camera Z moving

- code/modules/surgery/bodyparts/wounds/create_wound.dm
:cl: Kapu1178, Zonespace
refactor: Surgery, gauze mechanics, limb breaking mechanics, embedding mechanics
add: Vascular Recoupler (Fix O Vein)
add: Splints
add: You can now remove embedded items, splints, and bandages from yourself or other players by the Examine menu.
add: Bodyscanner, bodyscanner console, and bodyscanner display.
tweak: Sutures now instantly close small wounds, but otherwise do nothing.
del: Surgical drapes
del: Operating computers
/:cl:
> Missing baymed commit + changelog

- code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
- code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
- code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
:cl:
balance: Vent Pumps and Vent Scrubbers use 33% less power while idling.
balance: Thermomachine volume from 70 to 400 + (bin_rating * 200)
/:cl:
> Small tweaks to atmos equipment

- code/datums/diseases/advance/symptoms/sensory.dm
- code/datums/status_effects/_status_effect.dm
- code/datums/status_effects/debuffs/drunk.dm
- code/datums/status_effects/debuffs/speech_debuffs.dm
- https://github.com/tgstation/tgstation/pull/75459
Im fuckin dumb
:cl: MrMelbert
add: When you are drunk, the strength of your slurring now varies based on how drunk you are. Being "a little drunk" only rarely slurs your words, being average drunk is the same as the old effect, while being very drunk now slurs your words even more.
add: Some non-alcohol sources of slurring, such as concussions, now give "generic slurring" rather than "drunk slurring", which less resemble being drunk (ie, no burping).
add: Mind restoration now heals ALL slurring, rather than only drunk slurring (which includes cult / heretic slurring). /:cl:
/:cl:
> Drunk slurring scales based on how drunk you are (#75459)

- code/modules/client/client_procs.dm
Port of https://github.com/tgstation/tgstation/pull/77316
> Update client click handling for 514 (#77316)

- code/datums/status_effects/wound_effects.dm
:cl:
fix: Limping no longer gets stuck on your character after your legs are fixed.
/:cl:
> hotfix limping

- code/game/objects/items/storage/belt.dm
- code/modules/modular_computers/file_system/programs/ntmessenger.dm
:cl:
fix: Silicon 'PDAs' will now properly ring.
add: Medibelts can store Gauze now
/:cl:
> Fixes a petulent little runtime with messenger programs

- config/media/jsons/___EXAMPLE.json
Fixes the contents of the __EXAMPLE.json file for json music files to include duration by default, as it is required for files to properly play in the jukebox.
Done per @francinum 's request.
Not player facing
:cl: Gonenoculer5
fix: Modifies EXAMPLE.json to contain correct comment text relating to durations of music files.
/:cl:
> Fixes example JSON to contain duration

- code/modules/mob/living/carbon/carbon.dm
:cl:
fix: Fixed objects that render out of their tile rendering over blackness, when logically they should be invisible.
/:cl:
> Enables SEE_BLACKNESS when conflicting sight flags aren't used

- _maps/metastation.json
- code/controllers/configuration/entries/general.dm
- code/datums/map_config.dm
- code/modules/tgs/core/core.dm
- config/config.txt
- interface/interface.dm
- interface/skin.dmf
Adds Webmap button
Adds Codex button
map JSONS have a new key
:cl:
add: You can now view a map of the station with the 'Webmap' button in the top right cluster
code: Map JSONS must set the 'webmap_id' key for this to work.
add: You can now open the codex with the 'Codex' button, In the same place.
/:cl:
> Reorganizes the top right button cluster

- code/__DEFINES/mobs.dm
- code/datums/components/acid.dm
- code/datums/diseases/advance/symptoms/heal.dm
- code/datums/elements/kneecapping.dm
- code/game/objects/items.dm
- code/game/objects/items/stacks/medical.dm
- code/game/objects/items/storage/book.dm
- code/game/objects/structures/maintenance.dm
- code/modules/antagonists/wizard/equipment/soulstone.dm
- code/modules/assembly/mousetrap.dm
- code/modules/mob/living/blood.dm
- code/modules/mob/living/carbon/carbon_update_icons.dm
- code/modules/mob/living/carbon/damage_procs.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/life.dm
- code/modules/power/lighting/light.dm
- code/modules/religion/religion_sects.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
- code/modules/surgery/bodyparts/dismemberment.dm
- code/modules/surgery/bodyparts/wounds/_wounds.dm
- code/modules/surgery/bodyparts/wounds/burns.dm
- code/modules/surgery/bodyparts/wounds/cuts.dm
- code/modules/surgery/new_surgery/other.dm
:cl:
fix: Fixed a bug that might(?) have existed that caused wounds to not stop bleeding when they should.
fix: Damage overlays should now always be in the correct state. Cannot say the same for bleeding overlays, but, cope.
fix: Tendon repair surgery works.
/:cl:
> Fixes some wound bugs

- _maps/map_files/MetaStation/MetaStation.dmm
CMO's phone now has a data terminal
CE's disposal actually works
:cl:
fix:CMO's phone now has a data terminal
fix:CE's disposal actually works
fix:Medbay has fire extinguishers now
/:cl:
> Minor Meta Fixes

- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
- code/modules/atmospherics/ZAS/Atom.dm
- code/modules/atmospherics/ZAS/Debug.dm
- code/modules/atmospherics/ZAS/Turf.dm
- code/modules/atmospherics/ZAS/XGM/xgm_gas_mixture.dm
- code/modules/atmospherics/ZAS/Zone.dm
- code/modules/atmospherics/ZAS/zas_extras/inflatable.dm
Said quirk is pretty simple, when an airlock closes, the turf leaves the zone and takes it's share of air with it. Sounds fine, right? Well, it's fine until that share contains dangerous gas, because then when the airlock re-opens, it reintroduces the dangerous gas to the atmosphere.
My solution was actually pretty simple. Instead of using the simple zas_update_loc helper, I wrote some wrapper code around it specifically for doors to utilize when running close(). 
:cl:
fix: Doors of all kinds will no longer "trap" dangerous gas inside when closing.
/:cl:
> Fixes a decade old ZAS issue

- code/modules/clothing/head/helmet.dm
- code/modules/mob/living/carbon/human/monkey/monkey.dm
Ports various bits of TG PRs that got missed, somehow??
Primarily: https://github.com/tgstation/tgstation/pull/67517
fixes #484
fixes #486
:cl:
fix: Security Helmet flashlight behaviour is now a lot more reliable
/:cl:
> Helmet Light fixes

- code/__DEFINES/mobs.dm
- code/modules/antagonists/abductor/equipment/gland.dm
- code/modules/antagonists/heretic/heretic_living_heart.dm
- code/modules/antagonists/heretic/knowledge/starting_lore.dm
- code/modules/antagonists/heretic/structures/mawed_crucible.dm
- code/modules/atmospherics/ZAS/Plasma.dm
- code/modules/mining/lavaland/tendril_loot.dm
- code/modules/mob/living/brain/brain_item.dm
- code/modules/mob/living/carbon/damage_procs.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
- code/modules/surgery/bodyparts/injuries.dm
- code/modules/surgery/bodyparts/wounds/_wounds.dm
- code/modules/surgery/new_surgery/internal_organs.dm
- code/modules/surgery/new_surgery/robotics.dm
- code/modules/surgery/organs/_organ.dm
- code/modules/surgery/organs/augments_arms.dm
- code/modules/surgery/organs/augments_internal.dm
- code/modules/surgery/organs/eyes.dm
- code/modules/surgery/organs/liver.dm
- code/modules/surgery/organs/lungs.dm
- code/modules/surgery/organs/tongue.dm
:cl:
balance: Damaging a bodypart with a broken bone has a chance to deal damage to an organ inside.
balance: Damage that ignores armor (such as pressure damage) can no longer break bones or jostle bones.
balance: Tweaked the dismemberment formula for the 8th time
code: Removed organ/var/status
/:cl:
> Bone breaking tweaks

- code/modules/reagents/chemistry/machinery/chem_dispenser.dm
:cl:
fix: Added Ammonia to the chem dispenser
/:cl:
> add ammonia to the dispenser

- code/modules/tgui/tgui_alert.dm
- interface/interface.dm
Swaps out tgalert for stock alert, splits the message in 2
Wraps report info in a codeblock.
:cl:
fix: Issue reporter flow no longer overflows
/:cl:
> Fixes up the issue report flow

- code/_onclick/drag_drop.dm
- code/_onclick/hud/screen_objects.dm
- code/datums/storage/storage.dm
- code/game/objects/items.dm
- code/modules/mob/inventory.dm
:cl:
qol: Click-Drag can now be used to move items around inventories, including swapping which hand an item is holding.
/:cl:
> Click-Drag can now be used to consistently manipulate inventories.

- code/game/area/areas.dm
- code/game/area/areas/mining.dm
- code/game/area/areas/ruins/lavaland.dm
- code/game/area/areas/station.dm
- code/modules/mob/mob_defines.dm
:cl:
fix: Ambience automatically plays again.
tweak: Increased the volume of ambience (except lavaland)
/:cl:
> fixes ambience

- _maps/map_files/MetaStation/MetaStation.dmm
This should massively stabilize power
fixes #552
:cl:
fix: Atmospherics has a SMES unit to prop up it's exceptional power load.
/:cl:
> Atmospherics is now powered by a SMES unit.

- code/modules/jobs/job_types/assistant.dm
:cl:
fix: You will properly receive your Loadout Uniform as an Assistant
/:cl:
> Fix Assistant not getting their loadout uniform

- code/modules/client/preferences/species_features/basic.dm
- code/modules/mob/living/carbon/human/human_say.dm
:cl:
fix: Facial Hair Gradients can now be color picked again
fix: Wearing a non-mask object in your mask slot won't break your radio.
/:cl:
> Fixes facial hair gradient and GetVoice()

- code/game/machinery/data_disk.dm
- code/modules/research/designs/mecha_designs.dm
Adds the robotics flag for some mecha designs that weren't able to be printed due to the Fabricator/RnD removal update, but were printable previously. Also fixes being unable to print the Gygax targ board.
There's probably no reason for these modules to be unprintable, as they were printable pre-Fabricator.
**100% untested, I'm just assuming this is why because the other designs /are/ printable and /don't/ have the flag.**
:cl:
balance: you can print mecha designs that were printable pre-update now. Namely the mech laser, heavy mech laser and mech armours. You can now print the Gygax targ board.
/:cl:
> Adds the 'ROBOTICS' flag for some mecha designs

- code/modules/events/mass_hallucination.dm
The picked shared hallucination will be sent to observers.
This might matter for admins, but it's more to let observers in on the joke.
:cl:
add: Ghosts will now be told what the crew has collectively hallucinated.
/:cl:
> Mass Hallucinations now say which one occurred

- code/datums/browser.dm
Shouldn't change anything user facing. I hope.
> Browser datums no longer force HTML 4.1

- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/living.dm
:cl:
balance: Increased fall damage by alot, damage now varies by bodypart, accounting for all armor values.
/:cl:
> Increase fall damage by alot.

- code/__DEFINES/combat.dm
- code/datums/armor.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/head/crown.dm
- code/modules/clothing/head/hardhat.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/head/jobs.dm
- code/modules/clothing/spacesuits/hardsuits/_hardsuits.dm
- code/modules/clothing/spacesuits/hardsuits/engineering.dm
- code/modules/clothing/spacesuits/hardsuits/medical.dm
- code/modules/clothing/spacesuits/hardsuits/misc.dm
- code/modules/clothing/spacesuits/hardsuits/science.dm
- code/modules/clothing/spacesuits/hardsuits/security.dm
- code/modules/clothing/spacesuits/plasmamen.dm
- code/modules/clothing/spacesuits/specialops.dm
- code/modules/clothing/suits/armor.dm
- code/modules/clothing/suits/wiz_robe.dm
- code/modules/clothing/under/_under.dm
- code/modules/clothing/under/jobs/Plasmaman/command.dm
- code/modules/clothing/under/jobs/cargo.dm
- code/modules/clothing/under/jobs/command.dm
- code/modules/clothing/under/jobs/security.dm
- code/modules/mining/equipment/explorer_gear.dm
- code/modules/mod/mod_clothes.dm
- code/modules/mod/mod_control.dm
- code/modules/mod/mod_theme.dm
- modular_pariah/modules/customization/modules/clothing/head/jobs.dm
> remove WOUND and CONSUME damage types

- code/controllers/configuration/entries/game_options.dm
- code/modules/antagonists/malf_ai/datum_malf_ai.dm
- modular_pariah/master_files/code/modules/antagonist/_common/antag_datum.dm
:cl:
tweak: Traitor gets 1 gimmick objective, and can roll 1 additional kill or steal objective randomly.
/:cl:
> Tweak traitor objs

- _maps/map_files/MetaStation/MetaStation.dmm
says what it does on the tin
BEFORE:
AFTER:
accidental floating air alarms bad?
:cl:
del: a floating air alarm in security shooting gallery
/:cl:
> removes unnecessary air alarm in the hog shooting room

- code/_onclick/item_attack.dm
- code/modules/unit_tests/novaflower_burn.dm
:cl:
qol: You can no longer attack mobs without being in Combat Mode.
/:cl:
> You can't attack mobs without combat mode

- code/modules/interaction_particle/interaction_particle.dm
`has_active_hand()` is not meant to return `/obj/item/bodypart` (though it does)
Prevents possible bugs in the future (for example when someone wants a mob to always "have" an active hand.  Even if that arm was dismembered
:cl:
/:cl:
> Fixes get hand offset proc

- code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm
- code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
- code/modules/atmospherics/machinery/components/binary_devices/pressure_valve.dm
- code/modules/atmospherics/machinery/components/binary_devices/pump.dm
- code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
- code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
- code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
Unhelpful, Unused, Confusing??
Status was never set while also setting a control field, so this has no functional changes.
The `status` command returns early to save icon update costs, this has been moved before control field processing to prevent edge cases with causing changes that SHOULD result in updates, but never actually calling said updates.
`init` was both unused, and unsafe.
It was quick to do and provides more safety wrapping and prep for user packets.
:cl:
fix: 'status' field for ATMO-ECOM packets will now inhibit processing of other control fields.
del: 'init' control field has been removed.
/:cl:
> Removes ATMO-ECOM INIT, STAT now intercepts.

- code/modules/reagents/chemistry/goon_reagents/medicine_reagents.dm
- code/modules/reagents/chemistry/recipes/medicine.dm
- code/modules/reagents/chemistry/recipes/toxins.dm
fixes https://github.com/DaedalusDock/daedalusdock/issues/572
:cl:
fix: diphenhydramine, antihol, lipolicide, and anacea are craftable again.
fix: Antihol shows up in the codex.
/:cl:
> Fixes uncraftable chems

- code/controllers/subsystem/credits.dm
:cl:
fix: Having non-living mobs (such as the AI camera) will no longer break the EOR credits roll.
/:cl:
> fix credits bug

- code/modules/clothing/head/helmet.dm
Whoops.
fixes #559 
:cl:
fix: Security Helmets can now ACTUALLY have flashlights attached again.
/:cl:
> Security Helmets can now have flashlights attached again.

- code/modules/shuttle/navigation_computer.dm
Fixes #620
:cl:
fix: Whiteship custom landing spots work again.
/:cl:
> Fixes shuttle custom landing position do_after

- code/modules/admin/view_variables/debug_variables.dm
:cl: LemonInTheDark
tweak: Bitfield entries in View Variables show NONE instead of a blank entry if the field is empty.
/:cl:
> Adds NONE to empty bitflags in VV (#78355)

- code/controllers/subsystem/packetnets.dm
- code/modules/power/powernet.dm
SSpackets was incapable of hibernating since `queued_networks` was populated wrongly.
SS hibernation good
NUFC
:cl:
/:cl:
> Allows SSPackets to actually hibernate

- code/modules/reagents/chemistry/recipes/other.dm
:cl:
fix: Mutagen's recipe now works. For real this time.
/:cl:
> fix mutagen recipe

- code/modules/projectiles/projectile.dm
:cl:
fix: Fixed a bug that caused specific projectiles to collide with objects they shouldn't.
/:cl:
> small projectile bug

- code/modules/admin/view_variables/reference_tracking.dm
> Adds a proc that types can override to inject extra information into the refsearch
> This'll allow us to more easily track and deal with refs held by general datums, like callbacks.
> I've implemented a template example FOR callbacks, to provide an example and assist in solving future issues
> 
> Done to help lumipharon from TGMC, they were having trouble with this case.
No player facing changes
> Refsearch Info Injection (#78574)

- _maps/map_files/MetaStation/MetaStation.dmm
Kapu said it was an issue, and I just happen to have daedalus cloned locally. Convenient!
Uses access 1 and 4, whatever the hell that means in code. They're the same as the doors into the inner sec area, so it should be good.
Something something Warden/HoS/Cap shouldn't have to hand out EVA suits?
:cl:
fix: Secoffs should be able to access their EVA suits now.
/:cl:
> Makes Sec EVA Storage Use Sane Accesses

- code/modules/admin/verbs/SDQL2/SDQL_2.dm
- https://github.com/tgstation/tgstation/pull/78951
:cl: mc-oofert
fix: SDQL now displays turf locations instead of saying they are in nullspace
/:cl:
> Fix minor SDQL SELECT bug

- code/modules/mob/living/carbon/carbon.dm
:cl:
balance: Hitting someone with a thrown body now only knocks them down briefly instead of stunning + knocking down for 2 seconds
/:cl:
> Nerfs body throwing

- code/game/machinery/telecomms/machines/message_server.dm
- code/game/objects/items/manuals.dm
Fixes PDA server logging
Fixes missleping on the Supermatter Codex Book
:cl:
fix: PDA server now logs messages again
/:cl:
> Minor Fixes

- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
:cl:
fix: Inaprovaline will no longer "randomly" stop your heart (specific interaction that wasn't super rare)
/:cl:
> hotfix a chem interaction

- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/carbon/life.dm
:cl:
tweak: Adjusted volume of breathing in space.
fix: Fixed an issue where you could hear breathing in space even if you couldn't actually breathe (no internals, etc).
/:cl:
> minor breath changes

- code/controllers/subsystem/verb_manager.dm
- code/datums/verb_callbacks.dm
- https://github.com/tgstation/tgstation/pull/79964
:cl: KylerAce
code: verb callbacks will no longer execute if the original client disconnected
/:cl:
> makes verb callbacks not execute if the original client disconnected

- code/controllers/master.dm
- code/controllers/subsystem.dm
> i don't know if it even triggers for your usecases, but for keep_timing subsystems, they will see the hibernated ticks as "missed" ticks and run faster when they have work to "make up" for those missed ticks
:cl: MrStonedOne
fix: Fixed a bug with subsystems that caused some subsystems to fire faster than intended after having no work for some time.
/:cl:
> Fix interaction between SS_KEEP_TIMING and SS_HIBERNATE

- code/datums/components/carbon_sprint.dm
:cl:
fix: You can no longer sprint in space.
/:cl:
> sprinting in space no more

- code/modules/reagents/chemistry/equilibrium.dm
- code/modules/reagents/chemistry/recipes.dm
- https://github.com/tgstation/tgstation/pull/80178
This flag basically adjusts the temperature of the whole holder without taking into consideration its heat capacity. If the reactions thermic_constant was negative this flag would not function correctly as it would clamp the rate of change between 0 and CHEMICAL_MAX_TEMPERATURE and then apply it to the final temperature.
Now it clamps the final result(current temperature + rate of change) therefore reactions that uses this flag to cool down temps now works correctly.
https://github.com/tgstation/tgstation/issues/74667
The above point explains how the fix works. basically thermic_constant determines how much the holder temps cool down per unit of chem consumed. Cryostylane + oxygen reaction had this value at -50 which is way to low (cause …
> Reactions correctly respect the `REACTION_HEAT_ARBITARY` flag

- code/controllers/subsystem/ticker.dm
- code/modules/jobs/job_types/_job.dm
Players will not be seated in the same seat twice before all are filled.
Arrivals shuttles should feel less overfilled, I still want to go back and remap it but there's too many locks on Theseus right now.
:cl:
qol: Hermes Transport has instituted new seat filling algorithms to decrease lap-seating in long-range transport shuttles.
/:cl:
> Changes initial spawn wave logic

- code/modules/grab/grab_datum.dm
:cl:
fix: A rare bug with grabs not removing their effects on release.
/:cl:
> Potentially fix issue with grabs

- code/__DEFINES/maths.dm
:cl:
fix: The suit storage slot icon works correctly again.
/:cl:
> DIEDIEDIEDIEIDIEIDIEDIEIDIEDIEIDIEIDIEDIEIDIEIDIE

- code/modules/mob/living/simple_animal/slime/life.dm
- code/modules/mob/living/simple_animal/slime/slime.dm
- code/modules/reagents/chemistry/reagents/food_reagents.dm
Conceptual port of https://github.com/tgstation/tgstation/pull/80068
:cl: Profakos
del: Removes the slime's reagent holder. This will make them not slow down from somehow imbibing morphine or frostoil.
/:cl:
> Culls slime reagent support

- code/modules/surgery/bodyparts/_bodyparts.dm
:cl:
fix: Bodyparts are no longer affected by explosions directly when attached to a mob. The mob handles it.
/:cl:
> Fixes a bug with bodyparts and explosions

- code/datums/keybinding/human.dm
:cl:
fix: Default wield hotkey no longer conflicts with other default hotkeys.
/:cl:
> hotfix control for wielding

- code/modules/recycling/disposal/pipe.dm
Pipes can once more hurt unprotected mobs that get flushed into a disposal network. Respects if the mob is hiding in something, and also takes blunt armor into account.
Prevents people from escaping insane situations with disposal chutes, allows disposals to be used as a weapon, gives a reason to not throw yourself into a highly pressurized pneumatic machine that flings objects through dangerous pipes at high speeds.
:cl:
balance: Getting flushed into the disposal network damages mobs once more
/:cl:
> Disposal pipes hurt mobs again

- _maps/map_files/Theseus/Theseus.dmm
- code/__DEFINES/scent.dm
- code/__DEFINES/span.dm
- code/datums/elements/smell.dm
- code/game/objects/effects/decals/cleanable/humans.dm
- code/game/objects/effects/decals/cleanable/misc.dm
- code/game/objects/effects/decals/cleanable/robots.dm
- code/game/objects/items/cigs_lighters.dm
- code/game/objects/items/food/misc.dm
- code/modules/mob/dead/dead.dm
- code/modules/mob/living/carbon/human/human_helpers.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/emote.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/mob_helpers.dm
- code/modules/power/supermatter/nupermatter.dm
- code/modules/projectiles/guns/ballistic.dm
- code/modules/projectiles/guns/energy.dm
- code/modules/reagents/chemistry/goon_reagents/other_reagents.dm
- code/modules/unit_tests/create_and_destroy.dm
- tgui/packages/tgui-panel/styles/goon/chat-dark.scss
- tgui/packages/tgui-panel/styles/goon/chat-light.scss
:cl:
add: Ballistics now emit a long-lasting scent of gunpowder when fired.
add: Energy weapons now emit a short-lasting scent of ozone when fired.
qol: You won't see multiple smell messages in a single smell tick.
code: Cleaned up smell code.
/:cl:
> Surprise smelling content

- code/__DEFINES/sound.dm
- code/modules/mob/living/brain/brain_item.dm
- code/modules/mob/living/carbon/life.dm
- code/modules/mob/living/carbon/pain.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
- code/modules/surgery/bodyparts/dismemberment.dm
- code/modules/surgery/bodyparts/stump.dm
- code/modules/surgery/bodyparts/wounds/_wounds.dm
- code/modules/surgery/new_surgery/_surgery_step.dm
- code/modules/surgery/organs/heart.dm
- code/modules/surgery/organs/liver.dm
- code/modules/surgery/organs/lungs.dm
:cl:
fix: When you are knocked out from pain, you will stay knocked out until you recover enough.
qol: When you are entering shock, you will hear your heartbeat.
qol: Reduced time gap between pain messages.
qol: Pain message time gap will scale inversely proportional to the amount of pain you're in.
qol: Added more effects to earlier shock stages.
qol: Added a chat message for gasping caused by lung damage.
balance: Increased damage required to damage organs from external wounds.
balance: Reduced heart damage taken from irregular heartbeats.
/:cl:
> Health fixes & Experimental Balance

- code/game/turfs/turf.dm
- code/modules/mob/living/carbon/carbon.dm
:cl:
fix: You can no longer use self-grabs to propel yourself at the speed of light.
fix: You can no longer throw yourself.
/:cl:
> fix 2 exploits

- code/modules/mob/camera/camera.dm
Fixes moving down as camera mob
:cl:
fix: Camera mobs (AI, Blob, etc) can move down on multi Z maps now
/:cl:
> Fixes camera mob being unable to move down

- code/game/say.dm
- https://github.com/tgstation/tgstation/pull/81170
:cl: Ghommie
fix: Fixed text effects for runechat messages (the stuff enclosed in +, | and _ characters) sometimes not working.
/:cl:
> fix runechat being jank with emphasis

- code/controllers/subsystem/zas.dm
- code/datums/status_effects/debuffs/fire_stacks.dm
- code/modules/atmospherics/ZAS/Zone.dm
- code/modules/mob/living/carbon/human/species.dm
:cl:
fix: Damage from overheating would occasionally not update your health display.
/:cl:
> Zasstopscreamingplease

- code/game/objects/items/stacks/rods.dm
fixes Railings deconstruct into double their rods. #642
:cl:
fix: Railings no longer duplicate rods.
/:cl:
> Fixes the cost of railings

- _maps/map_files/Theseus/Theseus.dmm
- code/datums/components/food/edible.dm
- code/game/machinery/atm.dm
- code/game/objects/items/pinpointer.dm
- code/modules/admin/verbs/adminpm.dm
- code/modules/admin/verbs/debug.dm
- code/modules/antagonists/fugitive/fugitive_outfits.dm
- code/modules/antagonists/gang/outfits.dm
- code/modules/client/preferences/loadout/loadout_item/backpack.dm
- code/modules/clothing/outfits/ert.dm
- code/modules/clothing/outfits/standard.dm
- code/modules/grab/grab_object.dm
- code/modules/jobs/job_types/_job.dm
- code/modules/jobs/job_types/bartender.dm
- code/modules/mob/living/living.dm
- code/modules/unit_tests/create_and_destroy.dm
Closes #838
Closes #834 
Closes #833 
Closes #832 
:cl:
fix: Fixed IDs being broken
fix: Fixed a missing wire node in engine monitoring
fix: Fixed admin chat using the wrong css class
/:cl:
> pile of fixes

- code/_globalvars/admin.dm
- code/modules/admin/view_variables/view_variables.dm
:cl:
admin: GLOB.debug_disable_vv_icon_render can be used to disable VV's usage of GetFlatIcon at runtime.
/:cl:
> Admin VV Icon Render Disable Flag

- code/game/world.dm
Config error log gets moved into right place now.
NUFC
:cl:
/:cl:
> Config error log is now moved properly.

- code/datums/storage/storage.dm
- html/browser/common.css
- tgui/packages/tgui-panel/styles/goon/chat-dark.scss
Closes #844 
:cl:
fix: Storage objects no longer infinitely add action buttons.
fix: Some text effects scale with font size.
/:cl:
> fix storage action

- code/__DEFINES/bodyparts.dm
- code/modules/admin/verbs/selectequipment.dm
- code/modules/mob/living/brain/brain_item.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_stripping.dm
- code/modules/mob/living/carbon/human/species_types/vox.dm
- code/modules/mob/living/living.dm
- code/modules/reagents/chemistry/reagents/drug_reagents.dm
- code/modules/surgery/bodyparts/injuries.dm
- code/modules/surgery/machines/vitals_monitor.dm
- code/modules/surgery/new_surgery/internal_organs.dm
- code/modules/surgery/organs/_organ.dm
- code/modules/tables/tables_racks.dm
- code/modules/unit_tests/surgeries.dm
:cl:
fix: Admins can use equip outfit on IPCs.
fix: Vox blood, like, works.
fix: Retract Skin surgery works correctly on heads.
qol: Brain Revival surgery can now be done with most reagent containers, and only requires 5 units.
qol: Stripping is now able to be performed any time, unless you are in an aggressive grab and dont have combat mode turned on. In this case, you will attempt a fireman carry.
fix: Tables function correctly again. Notably, operating tables will turn off their vitals monitor if the patient leaves the table.
balance: Nicotine addiction builds 50% as fast as it used to.
/:cl:
> Lots of fixes

- code/__DEFINES/traits.dm
- code/game/atoms_movable.dm
- code/game/objects/buckling.dm
- code/game/objects/structures/railings.dm
- code/game/turfs/turf.dm
- code/modules/grab/grab_datum.dm
- code/modules/grab/grab_living.dm
- code/modules/grab/grab_movable.dm
- code/modules/grab/grab_object.dm
- code/modules/grab/grabs/grab_normal.dm
- code/modules/grab/grabs/grab_struggle.dm
- code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
- code/modules/tables/tables_racks.dm
- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/grabbing.dm
:cl:
fix: Neck-level grabs correctly move the victim.
fix: You can no longer move neck-level grab victims off your tile.
fix: Mobs buckled to a grabbed object now inherit the offset
qol: Cleaned up how repositioning grabbed movables works.
/:cl:
> grab fixes

- code/__DEFINES/dcs/signals/signals_mob/signals_mob_living.dm
- code/_onclick/hud/rendering/plane_master.dm
- code/datums/ai/generic/generic_behaviors.dm
- code/game/objects/items.dm
- code/game/objects/items/grenades/_grenade.dm
- code/game/objects/items/offhand.dm
- code/modules/antagonists/highlander/highlander.dm
- code/modules/cards/cardhand.dm
- code/modules/cards/deck/deck.dm
- code/modules/cards/singlecard.dm
- code/modules/client/preferences/monochrome_ghost.dm
- code/modules/grab/grabs/grab_normal.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/inventory.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/living/simple_animal/bot/cleanbot.dm
- code/modules/mod/modules/module_kinesis.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- code/modules/reagents/reagent_containers/hypospray.dm
- code/modules/research/machinery/_production.dm
- modular_pariah/master_files/code/game/gamemodes/objective.dm
:cl:
fix: Two-handed items function better.
fix: Fixed a sound not playing from fabricators.
fix: Cleanbots no longer get stuck spraying acid on specific blood decals.
fix: The monochrome ghost vision pref actually works (lol).
/:cl:
> Fixes two-handed items and runtimes

- code/modules/mob/living/carbon/human/human_defense.dm
Closes #887 
:cl:
fix: Attacking with an item will no longer always hit the chest.
/:cl:
> fix item attack chance

- code/datums/outfit.dm
- code/game/objects/items/storage/wallets.dm
:cl:
tweak: Roundstart wallets start open
fix: SecHUDs correctly display jobs again.
/:cl:
> wallet tweaks

- code/modules/mob/mob.dm
:cl:
fix: When you examine an object, mobs that cannot see the object you examined see a different message.
add: When you examine an object you're wearing, nearby mobs are told that item is yours.
add: When you examine an object inside of a storage container, nearby mobs are told you examined something inside of the storage container, but are not told what.
/:cl:
> Examine touch-ups

- code/modules/ambient_occlusion/turf_ao.dm
:cl:
fix: AO overlays no longer get stuck when turfs change. This was most obvious with the stellar body magnet.
/:cl:
> Fixes Ambient Occlusion overlays getting stuck on turf change.

- code/game/machinery/computer/security.dm
- code/modules/admin/admin_investigate.dm
> improves investigate_log

- config/game_options.txt
- config/maps.txt
> Fix configuration errors on master

- code/modules/clothing/head/jobs.dm
- code/modules/clothing/suits/armor.dm
:cl:
fix: Security armor is armor again.
/:cl:
> Fix old armor values (FUCK YOU BYOND)

- code/game/objects/items/cards_ids.dm
- code/modules/client/preferences/heterochromatic.dm
- code/modules/client/preferences/html_prefs/modules/quirks.dm
- code/modules/jobs/job_types/_job.dm
Closes #910
:cl:
fix: Heterochromia works again.
fix: The "Fingerprints" field of ID cards now uses the correct value.
/:cl:
> fix fingerprints & heterochromia

- code/datums/progressbar.dm
- code/game/machinery/doors/firedoor.dm
Closese #915 
:cl:
fix: Progress bars show up again.
/:cl:
> idk why i even changed this

- code/controllers/subsystem/garbage.dm
- code/datums/weakrefs.dm
- code/modules/mob/living/carbon/death.dm
:cl:
fix: Fix massive amount of runtimes thrown from mouse dragging out of the mouse pane.
fix: Fixed "safe" gibbing attempting to remove bodyparts and organs.
/:cl:
> Fixes runtimes

- code/modules/power/cable.dm
fixes #922
diagonal wire fucky
:cl:
fix: Cables now consider all neighbors that share diagonal-edge nodes, instead of just one inline tile.
/:cl:
> Diagonal cable patch

- code/modules/reagents/chemistry/equilibrium.dm
- code/modules/reagents/chemistry/holder.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Closes #945 
:cl:
fix: With a specific amount of reagents, a reaction could fail to occur and repeat infinitely.
/:cl:
> Fix occasional infinite reactions

- code/modules/mob/living/living.dm
- https://github.com/tgstation/tgstation/pull/79326
:cl: GPeckman
fix: Fixed a bug that could cause fire overlays to stick forever.
/:cl:
> fix fire overlay bug

- code/datums/dna.dm
- code/datums/mutations/_mutations.dm
- code/datums/mutations/body.dm
- code/datums/mutations/hulk.dm
- https://github.com/tgstation/tgstation/pull/80242
:cl: vinylspiders
fix: A rare bug that caused mutation effects to linger in weird ways.
/:cl:
> Mutation bug fix

- code/modules/atmospherics/machinery/airalarm.dm
Closes #493
:cl:
add: (consistency) Right-clicking an air alarm with an empty hand will now attempt to lock/unlock it.
/:cl:
> right click locks the air alarm

- .vscode/settings.json
- tgui/.yarn/sdks/typescript/bin/tsserver
- tgui/packages/tgui-bench/package.json
- tgui/packages/tgui-panel/settings/SettingsPanel.js
- tgui/packages/tgui/interfaces/NtosNetDownloader.js
- tgui/packages/tgui/interfaces/ParticleEdit/EntriesGenerators.tsx
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/ghost.tsx
- tgui/packages/tgui/interfaces/Uplink/GenericUplink.tsx
- tgui/packages/tgui/store.js
- tgui/yarn.lock
1. Fixes an issue reported with panel settings. This was caused by a stray `context` reference
2. Removes a couple other stray references
3. Fixes prettier path in settings.json
4. Fixes an unreported issue with node types in tgui-bench
Bug fixes
:cl:
fix: Chat settings should no longer bluescreen
/:cl:
> tgui cleanup

- code/game/objects/structures/memorial.dm
:cl:
add: Added Honkertron, a russian developer, to the list of the deceased devs in the credits.
/:cl:
> add honkertron to the immortal list

- tgui/packages/tgui/components/Chart.tsx
- tgui/packages/tgui/interfaces/PowerMonitor.jsx
Similiar issue that was in the original react port. I fixed this by just porting the TG chart component over and another PR (despite it being possibly ineffectual) https://github.com/tgstation/tgstation/pull/70434
Fixes #978
:cl:
fix: Ampcheck UI should work again
/:cl:
> tgui: fixes chart in power monitor

- code/_onclick/hud/screen_objects.dm
:cl:
fix: Clicking your inactive hand slot while holding an item in your active hand slot no longer outputs "You are unable to equip that!"
/:cl:
> fix small click bug

- code/modules/mob/dead/observer/observer.dm
:cl:
fix: You can no longer observe yourself.
fix: Observing no longer causes ambience runtimes.
/:cl:
> observe bugs

- code/game/objects/items.dm
- code/modules/mob/living/carbon/human/examine.dm
:cl:
add: You can now examine the items worn or held by someone.
/:cl:
> baystation gear examine

- code/modules/mob/mob.dm
:cl:
fix: Dead and Unconscious mobs won't broadcast their examine.
/:cl:
> fix dead mobs examining

- code/modules/surgery/organs/heart.dm
:cl:
fix: Mobs now enter cardiac arrest when in the maximum shock stage.
/:cl:
> Fix people not entering cardiac arrest at max shock stage

- tgui/packages/common/keys.ts
- tgui/packages/tgui/interfaces/PreferencesMenu/KeybindingsPage.tsx
The issue at least partly stems from the fact we're calling a function with params directly inside onClick. If you log it, it actually clicks every single one of these buttons on render. Normally you'd fix this just by making it an anonymous function `() => ..`; however, this functionality is somehow intrinsically tied into the component to a point beyond my comprehension and will to investigate. Therefore, the event chain is getting cancelled with stopPropagation() which successfully allows you to change keys.
I ported my own event.key enum so anyone can easily switch from the deprecated event.keyCode format that tgui uses. 
I ported parts of this PR as well https://github.com/tgstation/tgstation/pull/83710 for an upstream bug. (the parts left out won't be relevant if you're just going …
> Fixes keybindings UI

- code/__HELPERS/game.dm
- code/modules/hydroponics/hydroponics.dm
- code/modules/mob/living/living.dm
- https://github.com/tgstation/tgstation/pull/84006
:cl: Kapu1178, SyncIt21
balance: Hydroponics trays now hold water significantly longer.
qol: Many actions are safer from specific edge cases. You won't notice a difference.
/:cl:
> Hydroponics change and general QOL

- tgui/packages/tgui/components/ProgressBar.jsx
- tgui/packages/tgui/package.json
- tgui/tsconfig.json
- tgui/webpack.config.js
- tgui/yarn.lock
#1012 was caused by components still using string styles where react requires objects. I fixed the faulty component itself, so the issue shouldn't be noticed elsewhere.
Since this is a component issue and [tgui-core](https://www.npmjs.com/package/tgui-core) is ready, I'm adding the package. This is entirely optional, but @Kapu1178 and I spoke about this and they seemed to want to move forward. Now's the time
> [!NOTE]
> This does not actually use the tgui-core library, it's just adding it for the future
Fixes #1012
:cl:
fix: Fixed the pandemic UI bluescreening on beaker insert
/:cl:
> tgui: Pandemic issue, tg components

- code/game/objects/items/stacks/stack.dm
:cl:
fix: Splitting a stack no longer causes the new stack to have no materials.
/:cl:
> Fixes split out stacks not having any materials

- code/modules/mob/status_procs.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- code/modules/reagents/chemistry/reagents/toxin_reagents.dm
:cl:
balance: Haloperidol's residual sleeping effect has been capped at 3 minutes.
balance: Haloperidol is 20% as effective to sleeping targets.
/:cl:
> halochange

- code/game/atoms_movable.dm
This breaks canonical movement.
> Remove unneeded code

- code/game/objects/items/tanks/jetpack.dm
:cl:
balance: Jetpacks no longer provide a massive movespeed boost.
/:cl:
> jetpacks no longer make you move at the movespeed cap

- code/datums/blood_types.dm
:cl:
fix: O Positive and O Negative blood types are no longer named "AB+" and "AB-" respectively.
/:cl:
> fix bad blood name

- _maps/map_files/Theseus/Theseus.dmm
:cl:
fix: Removed the random wall in Dorms/Recreation
/:cl:
> Removes the random wall in Recreation

- code/__HELPERS/html.dm
:cl:
fix: Fixed an issue with some UI buttons where they would not trigger onClick actions due to a byond bug.
/:cl:
> fix bug with html buttons

- code/modules/mob/living/carbon/human/examine.dm
:cl:
fix: You can tell if someone is dead if you are within 1 tile of them.
/:cl:
> Examining dead fix

- _maps/map_files/Theseus/Theseus.dmm
fixes #1040
fixes #990
fixes #942
:cl:
fix: Connector port in botany maint storage closet is now on the right layer
fix: Central Medbay now has an air alarm
fix: You can no longer sneak into medbay with maint access via robotics maintenance.
/:cl:
> Various map fixes

- code/__DEFINES/three_dsix.dm
- code/game/objects/items/cigs_lighters.dm
- code/modules/reagents/chemistry/reagents/drug_reagents.dm
- code/modules/reagents/withdrawal/generic_addictions.dm
- code/modules/three_dsix/skills/coordination.dm
adds skill debuffs to withdrawals
adds skill buff to nicotine 
makes the cheap lighter burn chance be a skill roll
adds like, realism or something
:cl:
add: Skill debuffs to drug withdrawals
add: Handicraft skill boost due to nicotine (Daedalus Dock does not promote nicotine usage but it does not deny how cool and radical it is)
tweak: using a cheap lighter is now a handicraft check rather than pure RNG
tweak: the description of the handicraft skill has been changed
/:cl:
> extra skill stuff

- code/_onclick/hud/hud.dm
https://github.com/tgstation/tgstation/pull/85300
> Relative positions are calculated incorrectly in widescreen mode without this. To demonstrate, call
> 
> ```
> screen_loc_to_offset("EAST-4,SOUTH", null) = [-128,32]
> ```
> 
> When passed to offset_to_screen_loc, this will be clamped to (32,32)
> 
> ```
> offset_to_screen_loc(-128, 32, view = our_view) = "1,1"
> ```
> 
> And returned as 1,1 - moving the action button incorrectly.
> 
> By including our_view in the call to `screen_loc_to_offset`, this entire problem is avoided.
> ## Why It's Good For The Game
> 
> If someone sets a floating action button to be relative to EAST, SOUTH, or CENTER, they run into this bug. As far as I can tell, nothing currently does this and therefore it isn't meaningful, but I've run into this twice now …
> Ports tg#85300: Add our_view to screen_loc_to_offset in view_audit_buttons

- code/__DEFINES/dcs/signals/signals_turf.dm
- code/modules/lighting/lighting_source.dm
- code/modules/lighting/lighting_turf.dm
https://github.com/tgstation/tgstation/pull/84299
> ## About The Pull Request
> 
> Light sources stop emitting light if the tile in which the light source itself is located and all 4 adjacent tile block the light. This usually happens when a smoke grenade is thrown, or something went wrong in the chemistry again
>
> ## Why It's Good For The Game
> 
> You wont need to switch the lights twice to make them work after someone threw smoke grenades into the hallways anymore
🆑 Kocma-san
fix: Fixed lights stopping emitting light in some situations
/:cl:
> Ports tg#84299: Fixed lights stopping emitting light in some situations

- code/modules/projectiles/boxes_magazines/_box_magazine.dm
- code/modules/projectiles/boxes_magazines/internal/revolver.dm
https://github.com/tgstation/tgstation/pull/84247
> ## About The Pull Request
> 
> Box magazine code started from `.len` instead of `.len + 1` when refilling mags which would be fine if BYOND's `to` didn't include the last number. Unfortunately, it does, and if the mag has bullets when its refilled it will have one over the limit.
> 
> Russian revolver code had a type typo where ammo was added in nonexistent `/obj/item/ammo_box/magazine/internal/rus357`'s `Initialize` instead of `/obj/item/ammo_box/magazine/internal/cylinder/rus357`. It was pretty clearly was meant to start with a single bullet instead of 6, but neither removing existing ammo nor adding new was implemented properly. I stuff it with 5 blanks instead of making it empty because this will at least allow it to click with …
> Ports tg#84247: Fixes magazine overflow and russian roulette starting with 6(7) bullets

- code/modules/recycling/disposal/bin.dm
- code/modules/recycling/disposal/holder.dm
- code/modules/recycling/disposal/pipe.dm
- tgui/packages/tgui-panel/styles/goon/chat-dark.scss
:cl:
balance: Disposals damage has been HEAVVVVVVVVVVVVVIIILLLLLLLLYYYYYY reduced.
qol: Mobs in disposals will now cause loud banging to occur as they travel down and get hurt.
qol: You can now use the disposals UI from within the bin.
tweak: Adjusted the text styling of Hearing.
/:cl:
> Disposals tweaks

- code/modules/jobs/job_types/clown.dm
comedy restored
:cl:
fix: You can now properly set your job title back to Clown.
/:cl:
> fix clown title

- .github/workflows/ci_suite.yml
- dependencies.sh
- tools/bootstrap/python37._pth
- tools/bootstrap/python_.ps1
- tools/requirements.txt
Ports:
https://github.com/tgstation/tgstation/pull/72488
https://github.com/tgstation/tgstation/pull/67520
Big fuck off warning from 72488:
NUFC
:cl:
/:cl:
> Python-related Repo Gruntwork

- code/modules/mob/living/carbon/human/examine.dm
:cl:
fix: Mobs with active players no longer show as catatonic
/:cl:
> fix catatonic message

- code/__DEFINES/inventory.dm
- code/datums/elements/strippable.dm
- code/game/objects/items/storage/backpack.dm
- code/game/objects/items/storage/belt.dm
- code/modules/clothing/gloves/_gloves.dm
- code/modules/clothing/shoes/_shoes.dm
- code/modules/clothing/suits/_suits.dm
- code/modules/clothing/suits/bio.dm
- code/modules/clothing/suits/chaplainsuits.dm
- code/modules/clothing/suits/cloaks.dm
- code/modules/clothing/suits/ghostsheet.dm
- code/modules/clothing/suits/jacket.dm
- code/modules/clothing/suits/jobs.dm
- code/modules/clothing/suits/labcoat.dm
- code/modules/clothing/suits/shirt.dm
- code/modules/clothing/suits/straightjacket.dm
- code/modules/clothing/suits/toggles.dm
- code/modules/clothing/suits/utility.dm
- code/modules/clothing/under/_under.dm
- code/modules/mob/inventory.dm
- code/modules/mob/living/carbon/alien/larva/inventory.dm
- code/modules/mob/living/carbon/human/human_stripping.dm
- code/modules/mob/living/carbon/human/inventory.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/inventory.dm
- code/modules/mob/living/simple_animal/friendly/drone/inventory.dm
- code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
- code/modules/mob/living/simple_animal/slime/slime.dm
- code/modules/mod/mod_activation.dm
:cl:
add: The majority of items now have equip and unequip delays.
add: Unequipping someone else's shoes takes much longer if they are standing up.
code: Added support for unequip delays, does not cover all cases, will be buggy.
/:cl:
> Equipment delay minor overhaul

- code/__DEFINES/inventory.dm
- code/__DEFINES/traits.dm
- code/game/objects/items.dm
- code/game/objects/items/food/deepfried.dm
- code/modules/clothing/gloves/_gloves.dm
- code/modules/clothing/masks/_masks.dm
- code/modules/clothing/shoes/_shoes.dm
- code/modules/clothing/suits/_suits.dm
- code/modules/clothing/suits/chaplainsuits.dm
- code/modules/clothing/suits/cloaks.dm
- code/modules/clothing/suits/jacket.dm
- code/modules/clothing/suits/jobs.dm
- code/modules/clothing/suits/labcoat.dm
- code/modules/clothing/suits/toggles.dm
- code/modules/clothing/under/_under.dm
- code/modules/mob/inventory.dm
- code/modules/movespeed/modifiers/items.dm
:cl:
add: (Un)Equipping items such as gloves, backpacks, jackets, labcoats, and belts can now be done while moving.
/:cl:
> improvements to equipment slowdown

- code/__DEFINES/ai.dm
- code/datums/ai/_ai_controller.dm
- code/datums/ai/basic_mobs/basic_ai_behaviors/basic_attacking.dm
- code/datums/ai/generic/generic_behaviors.dm
- code/datums/ai/generic/generic_subtrees.dm
- code/datums/ai/hunting_behavior/hunting_behaviors.dm
- code/datums/ai/monkey/monkey_behaviors.dm
:cl:
fix: Monkeys will now eat food again, and not get stuck until something punches them in the face.
/:cl:
> Fix monkeys not being able to eat food then getting stuck forever

- code/game/objects/items.dm
:cl:
tweak: Blocking is no longer directional while prone.
/:cl:
> block while lying down

- code/_onclick/drag_drop.dm
- code/_onclick/hud/screen_objects.dm
- code/game/objects/items/defib.dm
- code/game/objects/items/devices/portable_chem_mixer.dm
- code/game/objects/items/tanks/watertank.dm
- code/modules/clothing/clothing.dm
- code/modules/mob/inventory.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mod/mod_control.dm
:cl:
fix: Fixed unequip delay affecting Storage and Pockets.
fix: Fixed being able to bypass unequip delay by using click-drag.
/:cl:
> Inventory bugfixes

- code/__HELPERS/verbs.dm
- code/modules/tgui/tgui_window.dm
:cl:
fix: Martial arts with help verbs now add help verbs again.
/:cl:
> Fixes add_verb() and remove_verb()

- code/modules/admin/verbs/admingame.dm
- code/modules/client/client_defines.dm
- code/modules/client/client_procs.dm
- code/modules/discord/discord_helpers.dm
- code/modules/mob/dead/new_player/new_player_panel.dm
:cl:
server: Discord account linking no longer hard-requires the panic bunker
/:cl:
> REOPEN: Allow viewing account link code without panic bunker

- code/modules/admin/admin_investigate.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/sql_message_system.dm
personal irritation
:cl:
admin: Notes/Messages Panel Verb.
/:cl:
> Message panel can be accessed without using Investigate

- code/modules/mob/mob_attacked_by.dm
- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/combat_stamina.dm
:cl:
fix: Stamina damage is dealt when attacking with items again.
/:cl:
> fixes stamina damage

- code/modules/mob/inventory.dm
:cl:
fix: You can no longer bypass movement speed from equip delays.
/:cl:
> Minor bug with equip delays

- code/_onclick/hud/screen_objects.dm
- code/game/objects/effects/cursor_catcher.dm
:cl:
fix: Kinesis works again
/:cl:
> Click catcher bugfix

- code/modules/mob/inventory.dm
:cl:
fix: quick equip works properly with items with equip delays
/:cl:
> fix quick equip

- tgui/packages/tgui/interfaces/MODsuit.jsx
When spreading `module`'s properties onto a react component via ` <Module {...module} active={active} />`, the author accidentally spread the `ref` prop. This kills the crab
This change just overwrites it to make sure there's no ref on the module
You can use your ui now
:cl:
fix: Fixed a modsuit bluescreen
/:cl:
> Fixes modsuits bluescreen

- code/_onclick/hud/alert.dm
- code/modules/mob/living/living.dm
:cl:
qol: Added a screen alert for being prone.
/:cl:
> Adds a screen alert for being prone

- code/modules/atmospherics/machinery/atmosmachinery.dm
- code/modules/atmospherics/machinery/components/tank.dm
- code/modules/shuttle/on_move.dm
- code/modules/shuttle/shuttle_rotate.dm
- https://github.com/tgstation/tgstation/pull/88413
> tank shuttle rotate

- code/modules/reagents/chemistry/goon_reagents/medicine_reagents.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- code/modules/reagents/chemistry/recipes/medicine.dm
- code/modules/reagents/reagent_containers/patch.dm
- code/modules/reagents/reagent_containers/pill.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
- code/modules/surgery/new_surgery/dental_implant.dm
:cl:
add: Silver Sulfadiazine, a fast-acting but inefficient topical burn healing reagent.
add: Styptic Powder, a fast-acting but inefficient topical brute healing reagent.
fix: Fixed coagulant effects causing errors.
balance: Doubled the metabolization rates of Dermaline and Meralyne. I felt they weren't impactful enough for how annoying they are to make.
/:cl:
> adds 2 new reagents

- code/modules/mob/living/living.dm
:cl:
add: Upon waking up, your eyes will be blurry for a short time.
/:cl:
> Give blurry vision when waking up.

- code/game/objects/items/defib.dm
- code/modules/unit_tests/snapback_sanity.dm
:cl:
qol: You can now take paddles from a defibrillator at any time.
qol: You can use AltClick to take paddles from a defibrillator.
qol: You can use the Toggle Paddles verb to take paddles from a defibrillator.
qol: You can now use the Use In Hand keybind to wield/unwield paddles (Restoring old behavior).
/:cl:
> Defib Cleanup

- _maps/map_files/Theseus/Theseus.dmm
- code/__DEFINES/jobs.dm
- code/controllers/subsystem/job.dm
- code/controllers/subsystem/ticker.dm
- code/modules/jobs/job_types/_job.dm
- code/modules/jobs/job_types/ai.dm
- code/modules/jobs/job_types/antagonists/nuclear_operative.dm
- code/modules/jobs/job_types/cyborg.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/ai/freelook/eye.dm
- code/modules/mob/living/silicon/ai/logout.dm
:cl:
tweak: Cyborgs spawn on the station.
qol: AI can now see their own eye.
/:cl:
> Refactors jobspawning

- code/__DEFINES/role_preferences.dm
- code/modules/client/preferences/antagonists.dm
:cl:
tweak: Antagonist preferences start ON.
fix: Sanguine Plague Outbreak didn't work due to an oversight.
/:cl:
> Antagonist preferences start on

- code/_onclick/hud/hud.dm
- code/modules/mob/inventory.dm
- code/modules/unit_tests/combat/__include.dm
- code/modules/unit_tests/combat/combat_nested_inventory.dm
:cl:
fix: Fixed a bug where click-dragging an item inside of a nested storage container to your hand would delete the item.
/:cl:
> Fix niche interaction with nested inventory deleting items

- code/game/gamemodes/blood_plague_outbreak.dm
:cl:
fix: The Sanguine Plague Outbreak gamemode no longer instantly ends.
/:cl:
> Fix Sanguine Plague Outbreak

- code/modules/slapcrafting/living_slapcraft.dm
- code/modules/slapcrafting/slapcraft_recipe.dm
THEY WERE GETTING SOFT GC'D LMAO
:cl:
fix: Slapcrafting works again.
/:cl:
> Fixes slapcrafting

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
- code/modules/surgery/bodyparts/bodypart_examine.dm
- code/modules/surgery/bodyparts/injuries.dm
- code/modules/surgery/bodyparts/wounds/_wounds.dm
- code/modules/surgery/bodyparts/wounds/bruises.dm
- code/modules/surgery/bodyparts/wounds/burns.dm
- code/modules/surgery/bodyparts/wounds/create_wound.dm
- code/modules/surgery/bodyparts/wounds/cuts.dm
- code/modules/surgery/bodyparts/wounds/lost_limb.dm
- code/modules/surgery/bodyparts/wounds/neck_bite.dm
- code/modules/surgery/bodyparts/wounds/punctures.dm
- daedalus.dme
:cl:
add: Unarmed attacks inflict different wounds based on their type.
add: 0-damage wounds (scars) persist for some time.
/:cl:
> wound cleanup

- code/modules/mob/living/carbon/human/human.dm
:cl:
add: The Afflicted - Thirst is now shown between Sated and Dead, with "Bloodlust" being represented by negative Thirst
/:cl:
> Bloodlust is now shown as negative thirst

- .github/workflows/run_integration_tests.yml
As it turns out, most servers running a variant of TG's CI script, are losing ~20 seconds on every Unit Test job to starting a completely redundant and misconfigured SQL docker container.
This PR stops doing that
NUFC
:cl:
/:cl:
> Saves 20 seconds on init due to reduced cargocult

- code/game/gamemodes/mixed.dm
- code/modules/client/preferences.dm
- code/modules/jobs/job_types/_job.dm
- code/modules/mod/mod_control.dm
- interface/interface.dm
:cl:
fix: Fixed AI and Cyborg not being selected by Divide Occupations.
fix: Fixed AI and Cyborg not correctly displaying in the preferences menu.
fix: Fixed modsuits not being removable. (pugman899)
fix: Fixed the Mixed gamemode's antagonist selection.
fix: Fixed the character limit regressing to 3.
/:cl:
> 030125bugs

- _maps/map_files/Theseus/Theseus.dmm
gives the janitor room power
Right now just connects the janitor office to the power grid, but plan to commit any other map bugs I see to it
its good for the game because its NOT good for janitor office to not be powered round start
:cl:
add: Wires to below the jani's room
/:cl:
> Adds wires

- code/game/gamemodes/heretics.dm
- code/game/gamemodes/mixed.dm
:cl:
tweak: Disabled Heretics.
/:cl:
> disables heretics

- code/modules/spooky/abilities/chilling_presence.dm
Closes #1246 
:cl:
fix: Chilling Presence ghost power works on awake targets.
/:cl:
> chilling presence works on awake targets

- code/datums/components/omen.dm
Replaces the Omen slip insta-kill with a more agony oriented "accident". Causes a head fracture and concussion, ontop of decent damage to the head and brain.
Less insta-kill game removal methods, while still keeping things like Bad Luck smites funny as shit, among other Omen uses.
:cl:
balance: Slipping while under a Omen curse no longer causes your head to pop like a grape
/:cl:
> Omen slip tweak

- code/modules/surgery/new_surgery/tend_wounds.dm
- code/modules/unit_tests/surgeries.dm
:cl:
balance: Reduces effectiveness of Tend Wounds.
/:cl:
> Tend Wounds tweak

- code/__HELPERS/stat_tracking.dm
- code/datums/browser.dm
- code/datums/profiling.dm
- code/game/machinery/newscaster/newspaper.dm
- code/game/objects/items/implants/implantpad.dm
- code/game/objects/items/storage/secure.dm
- code/modules/admin/admin.dm
- code/modules/admin/known_alts.dm
- code/modules/admin/tag.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/adminhelp.dm
- code/modules/admin/verbs/debug.dm
- code/modules/error_handler/error_viewer.dm
- html/admin/search.js
- modular_pariah/modules/admin/code/admin_help.dm
Converts a large batch of HTML UIs to `/datum/browser` usage away from quirk mode `browse()`
NUFC
:cl:
/:cl:
> HTML UI Fixup Batch 1

- code/datums/helper_datums/teleport.dm
- code/game/objects/buckling.dm
Ports this fix from tgstation, which closes #136  :
-  https://github.com/tgstation/tgstation/pull/87725
> `/proc/do_teleport(...)` now has extra checks for atoms with buckled mobs attempting to pass through it, assuring that they also pass through with the vehicle
> 
> `/atom/movable/proc/is_buckle_possible(...)` will skip density checks if the bucklable and the target share the same tile, because at that point it doesn't really matter (it also interfered with density checks when teleporting)
:cl:
fix: teleporting while buckling to something will bring the buckled object with you
fix: you can buckle to things if you are on the same turf
/:cl:
> Fixes teleporting while buckling mobs

- tgui/global.d.ts
- tgui/packages/tgui-panel/chat/renderer.jsx
- tgui/public/tgui.html
Ports a tgstation PR which fixes #1236:
- https://github.com/tgstation/tgstation/pull/89864
> Ports https://github.com/VOREStation/VOREStation/pull/16713
> No more NTOS error screens when you want to save your chat history
:cl: Vallat (ported by tontyGH)
fix: [516] saving the chat log will no longer crash tgchat
/:cl:
> Fixes chat log saving for 516 clients

- interface/skin.dmf
- tgui/packages/tgui-panel/settings/scaling.ts
Nudges the default chat separator up, and re-sinks the chat border.
:cl:
qol: The chat splitter has been adjusted to return it to the old size. You may need to reset or adjust the sizing splitters in your chat settings window.
/:cl:
> Chat size restoration

- code/modules/client/preferences/loadout/loadout.dm
- code/modules/client/preferences/loadout/loadout_item/loadout_item.dm
:cl:
fix: Loadouts save and load.
/:cl:
> Fixes loadout saving/loading

- code/__HELPERS/game.dm
- code/datums/progressbar.dm
- code/datums/storage/storage.dm
- code/game/machinery/_machinery.dm
- code/game/objects/items.dm
- code/modules/mob/inventory.dm
- code/modules/mob/living/carbon/inventory.dm
- code/modules/vending/_vending.dm
Partial port of
- https://github.com/tgstation/tgstation/pull/90895
:cl: Metek, Kapu1178
add: Removing items from and placing items into storage containers now has an animation.
fix: Public do_after() strips maptext.
/:cl:
> Mo' Animation

- code/modules/mob/mob.dm
`/mob/proc/send_appearance` was making a 5 second timer to remove the *appearance* from `hud_used.vis_holder.vis_contents` - which... does nothing, as it's the _container_ that's in the `vis_contents`. 
And now, due to vis_contents wrappers, we don't need an extra wrapper proc at all - we can just... call `remove_viscontents` directly on a timer, properly passing the _container_ as the argument, rather than the appearance.
also that `isatom(container)` was always false because `container` was always uninitialized. I presume it might've been intended to be `isatom(appearance)` but I'm not gonna make any assumptions.
better code that works properly is always good for the game, I think? prolly. hopefully.
no user-facing changes I believe.
> Fix `send_appearance` not properly removing the container from the vis holder

- code/_byond_version_compact.dm
DD is currently broken on OpenDream's CI due to it reporting the DM version as 515 (despite supporting various 516 features), and other codebases just skip this check for OD, so this does the same.
> Don't throw compile errors related to BYOND version for OpenDream

- code/controllers/subsystem/ticker.dm
- code/modules/client/playlist.dm
:cl:
fix: Fixed cases where title music would continue to play into the round.
/:cl:
> fix title music due to the ref being unclear

- code/__DEFINES/status_effects.dm
- code/datums/emotes.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/carbon_health.dm
- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/pain.dm
- code/modules/surgery/organs/_organ.dm
- code/modules/surgery/organs/stomach/_stomach.dm
:cl:
add: The "Starving" state of hunger now has the following effects: Stomach pain, vision impairment, an dry heaving. 
fix: Fixed an issue that caused pain messages induced by damaged organs to appear far more often than intended.
/:cl:
> Hunger additions

- code/modules/client/verbs/ooc.dm
Adds OOC back to OOC messages. The BYOND membership gem is no longer added to chat messages, but oh well.
:cl:
qol: OOC messages are now more clearly marked.
/:cl:
> OOC tag format changes

- tgui/packages/tgui/styles/base.scss
- tgui/packages/tgui/styles/colors.scss
- tgui/packages/tgui/styles/components/Button.scss
- tgui/packages/tgui/styles/functions.scss
- tgui/packages/tgui/styles/interfaces/Mecha.scss
- tgui/packages/tgui/styles/interfaces/NuclearBomb.scss
- tgui/packages/tgui/styles/layouts/Window.scss
- tgui/packages/tgui/styles/themes/book.scss
- tgui/packages/tgui/styles/themes/crt.scss
Like https://github.com/DaedalusDock/daedalusdock/pull/1344 but maintains hex color usage and adds functions identical to SCSS's old darken() and lighten().
> Fixes SASS warnings while preserving current behavior.

- code/datums/components/caltrop.dm
- code/game/objects/effects/decals/cleanable/misc.dm
- code/game/objects/items/dice.dm
- code/game/objects/items/stacks/sheets/glass.dm
- code/modules/food_and_drinks/drinks/drinks/bottle.dm
- code/modules/food_and_drinks/plate.dm
- code/modules/hydroponics/plants/towercap.dm
- code/modules/mob/living/basic/vermin/cockroach.dm
- code/modules/power/lighting/light_items.dm
- code/modules/reagents/reagent_containers/syringes.dm
:cl:
add: Syringes can now be stepped on while barefoot, contaminated syringes will infect the victim.
tweak: All "caltrop" items now no longer trigger while walking. This does NOT apply to crawling over them.
/:cl:
> Stepping on needles

- code/controllers/subsystem/augury.dm
- code/controllers/subsystem/processing/obj_tab_items.dm
`SSaugury` and `SSobj_tab_items` accidentally included `SS_HIBERNATE` as a run level instead of a flag...
Also, I included `observers_given_action` in `SSaugury`'s `hibernate_checks` bc it can cause observer hard deletes otherwise.
things working properly is nice
No player-facing changes.
> Fix a couple of subsystems improperly setting `SS_HIBERNATE`

- code/datums/keybinding/_keybindings.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/living/carbon/human/emote.dm
:cl:
fix: Players are no longer alerted that keys which are unbound by default need binding.
/:cl:
> fix keybinds crying for no raisin

- code/__DEFINES/alerts.dm
- code/_onclick/hud/alert.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/living.dm
:cl:
del: Removed the ability to succumb.
add: Using the ghost verb while unconscious now prompts you if you really want to ghost.
/:cl:
> Removes succumbing

- code/modules/dreams/detective_nightmare.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/living.dm
- code/modules/mood/mood_events/health_events.dm
:cl:
fix: The Scrying Orb allows you to re-enter your body.
add: The Private Investigator gets a negative moodlet for having a nightmare.
/:cl:
> 082225bugs
